-- P8.5-44 · Moderation. Run once in the Supabase SQL editor, after clubs.sql,
-- clubs-2.sql and profile-plus.sql; then moderation-words.sql (the lists,
-- generated by scripts/build-moderation.ts; re-run it whenever they change).
-- Safe to run again. Tested headless by scripts/verify-moderation.ts.
--
-- Everything is checked HERE, in the database, so no app (old, modified or
-- not ours) can get around it, and nothing is sent to any other service (the
-- maintainer's call, 1 Oct 2026: local only). Three kinds of check:
--
--  · NAMES (usernames; club names, tags and descriptions; a profile's status,
--    pronouns and about): strict. A listed word is refused, however it's
--    disguised: any case or accent, digits for letters (f4ck), letters
--    repeated (fuuuck), separators (f.u.c.k), run into other words
--    (xXfuckXx), and the severe ones even inside a word ("Lafuckda"). An
--    innocent word that holds one (Scunthorpe) is on the allowlist.
--  · UNSURE NAMES go to the review inbox instead (mod_flags), still allowed:
--    a "maybe" word, or a group of people next to something hostile
--    ("IslamHater2121" holds no listed word, and is plainly wrong).
--  · CHAT (a club's, when its clean language is on): a listed word is swapped
--    for a funny one ("Lafuckda" → "Lafudgeda"), never refused, and no line
--    is added under it. Only what's written plainly or with simple swaps (f4ck,
--    fuuuck) is caught: a player who really wants to can still write around
--    it, and an ordinary player never meets the filter.
--
-- Plus: reports (any player or club, from its page), the inbox the
-- maintainer works through (profiles.is_admin, set by him in the SQL
-- editor), forced renames and bans.

create extension if not exists unaccent with schema extensions;

-- ── The lists (filled by moderation-words.sql) ────────────────────────────────
-- word: the letters (mod_letters); kind 'hard' (refused / swapped) or
-- 'review' (a name goes to the inbox); embed: caught inside other words too;
-- rx: the name regex over mod_letters, each run of a letter allowed to
-- stretch but not to shrink (so "nigger" never matches Niger or Nigeria);
-- pattern: the chat regex over the message as written (accents, simple swaps
-- and stretching built in); replacement: what chat shows instead. rx and
-- pattern are built by scripts/build-moderation.ts, which says why each way.
create table if not exists public.mod_words (
  word        text primary key,
  shown       text not null,
  kind        text not null check (kind in ('hard', 'review')),
  lang        text not null default 'en',
  embed       boolean not null default false,
  rx          text not null,
  pattern     text,
  replacement text,
  source      text not null default 'own'
);
create table if not exists public.mod_allow (word text primary key);
-- The lists folded into a few big alternations (see compiled() in
-- build-moderation.ts): the name check runs these, not a regex per word.
create table if not exists public.mod_compiled (kind text primary key, rx text not null);
-- Nobody reads the lists from the app: the checks below are the only way in
-- (security definer). The old swear table from clubs-2.sql goes with them.
alter table public.mod_words    enable row level security;
alter table public.mod_allow    enable row level security;
alter table public.mod_compiled enable row level security;
drop table if exists public.club_swears;

-- ── Normalising ───────────────────────────────────────────────────────────────
-- Lower case, no accents, the common symbol swaps undone ($ s, 7 t, | l), and
-- a digit or symbol standing for a vowel turned into *, which the patterns
-- read as any vowel ("f4ck"). Repeated letters are kept: the patterns allow
-- for them.
create or replace function public.mod_norm(t text) returns text
language sql stable set search_path = public, extensions
as $$ select translate(lower(unaccent(coalesce(t, ''))), '4@31!0$57+|', '******sttl') $$;

-- The letters alone, separators gone: "f.u.u.c.k" → "fuuck" (which the patterns match).
create or replace function public.mod_letters(t text) returns text
language sql stable set search_path = public, extensions
as $$ select regexp_replace(mod_norm(t), '[^a-z*]', '', 'g') $$;

-- A name's words: split at anything that isn't a letter or a swap digit, and
-- at a change from lower to upper case ("IslamHater" → islam, hater).
create or replace function public.mod_tokens(t text) returns text[]
language sql stable set search_path = public, extensions
as $$
  select coalesce(array_agg(w), '{}') from (
    select mod_letters(x) as w
    from regexp_split_to_table(regexp_replace(coalesce(t, ''), '([a-z])([A-Z])', '\1 \2', 'g'), '[^A-Za-z0-9@$!|+À-ɏ]+') as x
  ) s where w <> ''
$$;

create or replace function public.mod_rx(k text) returns text
language sql stable security definer set search_path = public
as $$ select coalesce((select rx from mod_compiled where kind = k), 'x^') $$;

-- ── Names ─────────────────────────────────────────────────────────────────────
-- 'blocked', 'review' or 'ok'. hard_any runs over the name's letters joined
-- up ("xXfuckXx"); *_long inside each of its words; *_tok over each word
-- whole, with the endings a word may carry ("fuckers"). build-moderation.ts
-- says which words go in which, and why.
create or replace function public.mod_check_name(t text) returns text
language plpgsql stable security definer set search_path = public, extensions
as $$
declare
  s text := mod_letters(t);
  toks text[] := mod_tokens(t);
  a record;
  i int;
begin
  if coalesce(trim(t), '') = '' then return 'ok'; end if;
  -- Innocent words first out of the way (Scunthorpe, Picasso).
  for a in select word from mod_allow loop
    s := replace(s, a.word, '');
    for i in 1 .. coalesce(array_length(toks, 1), 0) loop toks[i] := replace(toks[i], a.word, ''); end loop;
  end loop;
  if s ~ mod_rx('hard_any') or exists (select 1 from unnest(toks) k where k ~ mod_rx('hard_tok') or k ~ mod_rx('hard_long')) then return 'blocked'; end if;
  -- Not sure: a "maybe" word, or a group of people next to something hostile.
  if exists (select 1 from unnest(toks) k where k ~ mod_rx('review_tok') or k ~ mod_rx('review_long')) then return 'review'; end if;
  if exists (select 1 from unnest(toks) k where k ~ mod_rx('identity_tok') or k ~ mod_rx('identity_long'))
     and exists (select 1 from unnest(toks) k where k ~ mod_rx('hostile_tok') or k ~ mod_rx('hostile_long')) then
    return 'review';
  end if;
  return 'ok';
end $$;

-- ── Chat ──────────────────────────────────────────────────────────────────────
-- Each listed word swapped for its replacement; an allowlisted word is set
-- aside first so a swap can't land inside it, then put back.
create or replace function public.mod_clean_chat(t text) returns text
language plpgsql stable security definer set search_path = public, extensions
as $$
declare
  out text := coalesce(t, '');
  kept text[] := '{}';
  w record; hit text[]; n int := 0;
begin
  -- Almost every message holds no listed word anywhere: one test, and done.
  if mod_letters(out) !~ mod_rx('chat_any') then return out; end if;
  for w in select word from mod_allow loop
    loop
      hit := regexp_match(out, w.word, 'i');
      exit when hit is null or n > 200;
      n := n + 1;
      kept := kept || hit[1];
      out := regexp_replace(out, w.word, chr(1) || array_length(kept, 1) || chr(2), 'i');
    end loop;
  end loop;
  -- Longest first, so "motherfucker" goes whole before "fuck" can take part
  -- of it. A whole-word pattern captures the word's ending (\1), kept after
  -- the replacement: "dicks" → "dinguss" reads better than losing the s.
  -- ponytail: a regex per listed word, only for the rare message the test
  -- above lets through; prefilter by word if chat ever gets busy.
  for w in select pattern, replacement, embed from mod_words where kind = 'hard' and pattern is not null order by length(word) desc loop
    out := regexp_replace(out, w.pattern, replace(w.replacement, '\', '') || case when w.embed then '' else '\1' end, 'gi');
  end loop;
  for i in 1 .. coalesce(array_length(kept, 1), 0) loop
    out := replace(out, chr(1) || i || chr(2), kept[i]);
  end loop;
  return out;
end $$;

-- ── The inbox, reports and bans ───────────────────────────────────────────────
alter table public.profiles add column if not exists is_admin    boolean not null default false;
alter table public.profiles add column if not exists banned_at   timestamptz;
alter table public.profiles add column if not exists must_rename boolean not null default false;

-- One open entry per thing: a player, a club or a message, flagged by the
-- checks above ('auto') or by players ('report'), with how many reported it.
create table if not exists public.mod_flags (
  id          bigint generated always as identity primary key,
  target_type text not null check (target_type in ('player', 'club', 'message')),
  target_id   text not null,
  text        text,
  reason      text not null,
  source      text not null check (source in ('auto', 'report')),
  reports     integer not null default 0,
  status      text not null default 'open' check (status in ('open', 'dismissed', 'actioned')),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create unique index if not exists mod_flags_open on public.mod_flags (target_type, target_id) where status = 'open';
alter table public.mod_flags enable row level security;

create table if not exists public.mod_reports (
  id          bigint generated always as identity primary key,
  reporter    uuid not null references public.profiles(id) on delete cascade,
  target_type text not null check (target_type in ('player', 'club')),
  target_id   text not null,
  reason      text not null check (reason in ('name', 'hate', 'harassment', 'cheating', 'other')),
  details     text check (char_length(details) <= 300),
  created_at  timestamptz not null default now(),
  unique (reporter, target_type, target_id)
);
alter table public.mod_reports enable row level security;

create or replace function public.mod_flag(p_type text, p_id text, p_text text, p_reason text, p_source text)
returns void language plpgsql security definer set search_path = public
as $$
begin
  insert into mod_flags (target_type, target_id, text, reason, source, reports)
    values (p_type, p_id, p_text, p_reason, p_source, case when p_source = 'report' then 1 else 0 end)
  on conflict (target_type, target_id) where status = 'open'
    do update set reports = mod_flags.reports + case when p_source = 'report' then 1 else 0 end,
                  reason = case when p_source = 'report' then p_reason else mod_flags.reason end,
                  text = coalesce(excluded.text, mod_flags.text), updated_at = now();
end $$;
revoke all on function public.mod_flag(text, text, text, text, text) from public, anon, authenticated;

-- A player reports a player or a club: once each (a second report of the same
-- thing by the same player is ignored), and it joins the inbox.
create or replace function public.report(p_type text, p_id text, p_reason text, p_details text)
returns void language plpgsql security definer set search_path = public
as $$
declare shown text;
begin
  perform club_player_check();
  if p_type not in ('player', 'club') then raise exception 'BAD_TARGET'; end if;
  if p_type = 'player' and p_id = auth.uid()::text then raise exception 'NOT_ALLOWED'; end if;
  insert into mod_reports (reporter, target_type, target_id, reason, details)
    values (auth.uid(), p_type, p_id, p_reason, nullif(trim(left(coalesce(p_details, ''), 300)), ''))
  on conflict do nothing;
  if not found then return; end if;
  shown := case p_type when 'player' then (select username from profiles where id::text = p_id)
                       else (select name || ' [' || tag || ']' from clubs where id::text = p_id) end;
  perform mod_flag(p_type, p_id, shown, p_reason, 'report');
end $$;

create or replace function public.is_moderator() returns boolean
language sql stable security definer set search_path = public
as $$ select coalesce((select is_admin from profiles where id = auth.uid()), false) $$;

-- The inbox: what's open, most-reported first.
create or replace function public.mod_inbox()
returns table (id bigint, target_type text, target_id text, text text, reason text, source text, reports integer, created_at timestamptz,
  details text[])
language plpgsql stable security definer set search_path = public
as $$
begin
  if not is_moderator() then raise exception 'NOT_ALLOWED'; end if;
  return query
    select f.id, f.target_type, f.target_id, f.text, f.reason, f.source, f.reports, f.created_at,
      array(select r.reason || coalesce(': ' || r.details, '') from mod_reports r where r.target_type = f.target_type and r.target_id = f.target_id order by r.created_at desc limit 10)
    from mod_flags f where f.status = 'open'
    order by f.reports desc, f.created_at;
end $$;

-- What the moderator does with an entry: let it be, make the player pick a
-- new name (the old one goes at once), ban the player, or close the club.
create or replace function public.mod_act(p_flag bigint, p_action text)
returns void language plpgsql security definer set search_path = public
as $$
declare f mod_flags%rowtype;
begin
  if not is_moderator() then raise exception 'NOT_ALLOWED'; end if;
  select * into f from mod_flags where id = p_flag and status = 'open';
  if f.id is null then raise exception 'NO_SUCH_FLAG'; end if;
  if p_action = 'dismiss' then
    update mod_flags set status = 'dismissed', updated_at = now() where id = f.id; return;
  end if;
  if p_action = 'rename' and f.target_type = 'player' then
    update profiles set username = 'player-' || substr(md5(id::text), 1, 6), must_rename = true where id::text = f.target_id;
  elsif p_action = 'ban' and f.target_type = 'player' then
    update profiles set banned_at = now(), username = 'player-' || substr(md5(id::text), 1, 6) where id::text = f.target_id;
    delete from club_members where user_id::text = f.target_id;
    update profiles set club_tag = null where id::text = f.target_id;
  elsif p_action = 'close' and f.target_type = 'club' then
    update profiles set club_tag = null where id in (select user_id from club_members where club_id::text = f.target_id);
    delete from clubs where id::text = f.target_id;
  elsif p_action = 'rename' and f.target_type = 'club' then
    update clubs set name = 'Club ' || substr(md5(id::text), 1, 6), about = null where id::text = f.target_id;
  else
    raise exception 'BAD_ACTION';
  end if;
  update mod_flags set status = 'actioned', updated_at = now() where id = f.id;
end $$;

-- A banned player can't hold a club, join one, write in a chat or save a run.
create or replace function public.club_player_check()
returns void language plpgsql stable security definer set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'NOT_SIGNED_IN'; end if;
  if exists (select 1 from profiles where id = auth.uid() and coalesce(is_guest, false)) then raise exception 'GUEST'; end if;
  if exists (select 1 from profiles where id = auth.uid() and banned_at is not null) then raise exception 'BANNED'; end if;
end $$;

create or replace function public.mod_not_banned() returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  if exists (select 1 from profiles where id = new.user_id and banned_at is not null) then raise exception 'BANNED'; end if;
  return new;
end $$;
drop trigger if exists runs_not_banned on public.runs;
create trigger runs_not_banned before insert on public.runs for each row execute function public.mod_not_banned();
drop trigger if exists club_messages_not_banned on public.club_messages;
create trigger club_messages_not_banned before insert on public.club_messages for each row execute function public.mod_not_banned();

-- ── Where the checks run ──────────────────────────────────────────────────────
-- A name that's refused raises BAD_WORD (the app answers in the player's
-- language); an unsure one is let through and flagged. A rename forced by the
-- moderator is lifted once the player picks a name that passes.
create or replace function public.mod_profile_name() returns trigger
language plpgsql security definer set search_path = public
as $$
declare v text;
begin
  if new.username is distinct from coalesce(old.username, '') and new.username is not null then
    -- The moderator's own placeholder ("player-1a2b3c") is ours, not the player's.
    if new.username !~ '^player-[0-9a-f]{6}$' then
      v := mod_check_name(new.username);
      if v = 'blocked' then raise exception 'BAD_WORD'; end if;
      if v = 'review' then perform mod_flag('player', new.id::text, new.username, 'name', 'auto'); end if;
      new.must_rename := false;
    end if;
  end if;
  return new;
end $$;
drop trigger if exists profiles_name_check on public.profiles;
create trigger profiles_name_check before insert or update of username on public.profiles
  for each row execute function public.mod_profile_name();

create or replace function public.mod_profile_look() returns trigger
language plpgsql security definer set search_path = public
as $$
declare part text; v text; worst text := 'ok';
begin
  foreach part in array array[new.status, new.pronouns, new.about] loop
    v := mod_check_name(part);
    if v = 'blocked' then raise exception 'BAD_WORD'; end if;
    if v = 'review' then worst := 'review'; end if;
  end loop;
  if worst = 'review' then perform mod_flag('player', new.user_id::text, concat_ws(' · ', new.status, new.pronouns, new.about), 'profile', 'auto'); end if;
  return new;
end $$;
drop trigger if exists profile_looks_check on public.profile_looks;
create trigger profile_looks_check before insert or update of status, pronouns, about on public.profile_looks
  for each row execute function public.mod_profile_look();

-- The favourite player is typed freely and shown on the public profile.
create or replace function public.mod_profile_detail() returns trigger
language plpgsql security definer set search_path = public
as $$
declare v text := mod_check_name(new.favourite_player);
begin
  if v = 'blocked' then raise exception 'BAD_WORD'; end if;
  if v = 'review' then perform mod_flag('player', new.user_id::text, new.favourite_player, 'profile', 'auto'); end if;
  return new;
end $$;
drop trigger if exists profile_details_check on public.profile_details;
create trigger profile_details_check before insert or update of favourite_player on public.profile_details
  for each row execute function public.mod_profile_detail();

create or replace function public.mod_club_name() returns trigger
language plpgsql security definer set search_path = public
as $$
declare part text; v text; worst text := 'ok';
begin
  foreach part in array array[new.name, new.tag, new.about] loop
    v := mod_check_name(part);
    if v = 'blocked' then raise exception 'BAD_WORD'; end if;
    if v = 'review' then worst := 'review'; end if;
  end loop;
  if worst = 'review' then perform mod_flag('club', new.id::text, new.name || ' [' || new.tag || ']', 'name', 'auto'); end if;
  return new;
end $$;
drop trigger if exists clubs_name_check on public.clubs;
create trigger clubs_name_check before insert or update of name, tag, about on public.clubs
  for each row execute function public.mod_club_name();

-- The chat: swapped, never refused (replaces clubs-2.sql's first filter).
create or replace function public.club_clean_message() returns trigger
language plpgsql security definer set search_path = public
as $$
declare out text;
begin
  if not coalesce((select clean_chat from clubs where id = new.club_id), true) then return new; end if;
  out := mod_clean_chat(new.body);
  if out is distinct from new.body then new.body := left(out, 500); new.cleaned := true; end if;
  return new;
end $$;

-- For the app's name fields: tells them before they save (the triggers above
-- still decide). Only the verdict comes back, never which word.
create or replace function public.check_name(p_text text) returns text
language sql stable security definer set search_path = public
as $$ select mod_check_name(p_text) $$;

grant execute on function public.report(text, text, text, text) to authenticated;
grant execute on function public.mod_inbox() to authenticated;
grant execute on function public.mod_act(bigint, text) to authenticated;
grant execute on function public.is_moderator() to authenticated;
grant execute on function public.check_name(text) to anon, authenticated;
