/**
 * The public build's twins of the app's tables keyed by a club's real name
 * (P8.5 Wave D, the altered names). In the public build Metro resolves each
 * of these to its twin (metro.config.js LEGAL_SWAPS), so no real club name is
 * bundled, and lookups by a club's (altered) name still find it:
 *
 *   src/data/stadiums.ts         → stadiums.legal.ts         the grounds; a ground's
 *                                  own name is often a mark ("Allianz Arena",
 *                                  "Juventus Stadium"), so it becomes "<city> Stadium"
 *   src/data/club-codes.ts       → club-codes.legal.ts       no hand overrides (they
 *                                  spell real names); codes come from the altered name
 *   src/data/europe-countries.ts → europe-countries.legal.ts the club → country maps
 *
 * From scripts/legal-names/clubs.csv (real → altered, by name). A real key the
 * table has no altered name for is left out: it would be a real name.
 * Run by build-db after it writes players_legal.db; or on its own:
 *   npx tsx scripts/build-legal-twins.ts
 */
import { readFileSync, writeFileSync } from 'fs'
import path from 'path'
import { STADIUMS } from '../src/data/stadiums'
import { EUROPE_CLUB_COUNTRY, CL_CLUB_COUNTRY } from '../src/data/europe-countries'

const ROOT = path.join(__dirname, '..')
const csv = readFileSync(path.join(__dirname, 'legal-names/clubs.csv'), 'utf8').split(/\r?\n/).slice(1)
const altered = new Map<string, string>()
for (const line of csv) {
  if (!line) continue
  const cells: string[] = []; let f = '', q = false
  for (let i = 0; i < line.length; i++) {
    const ch = line[i]
    if (q) { if (ch === '"' && line[i + 1] === '"') { f += '"'; i++ } else if (ch === '"') q = false; else f += ch }
    else if (ch === '"') q = true
    else if (ch === ',') { cells.push(f); f = '' }
    else f += ch
  }
  cells.push(f)
  if (cells[1] && cells[2]) altered.set(cells[1], cells[2])
}
const HEAD = (from: string) => `// GENERATED by scripts/build-legal-twins.ts from scripts/legal-names/clubs.csv —\n// don't edit by hand. The public build's twin of ${from} (metro.config.js swaps it in).\n/* eslint-disable */\n`
const rekey = <T>(table: Record<string, T>, value: (real: string, v: T, alt: string) => T): Record<string, T> => {
  const out: Record<string, T> = {}
  for (const [real, v] of Object.entries(table)) { const alt = altered.get(real); if (alt) out[alt] = value(real, v, alt) }
  return out
}

const stadiums = rekey(STADIUMS, (_, s, alt) => ({ ...s, name: s.city ? `${s.city} Stadium` : `${alt} Ground` }))
writeFileSync(path.join(ROOT, 'src/data/stadiums.legal.ts'),
  HEAD('src/data/stadiums.ts') + `export type Stadium = { name: string; capacity?: number; city?: string; country?: string }\n\nexport const STADIUMS: Record<string, Stadium> = ${JSON.stringify(stadiums, null, 2)}\n`)

const codes = readFileSync(path.join(ROOT, 'src/data/club-codes.ts'), 'utf8')
const twin = codes.replace(/export const CLUB_CODE_OVERRIDES: Record<string, string> = \{[\s\S]*?\n\}/, 'export const CLUB_CODE_OVERRIDES: Record<string, string> = {}')
if (twin === codes) throw new Error('club-codes.ts changed shape: the overrides table was not found')
writeFileSync(path.join(ROOT, 'src/data/club-codes.legal.ts'), HEAD('src/data/club-codes.ts') + twin)

writeFileSync(path.join(ROOT, 'src/data/europe-countries.legal.ts'), HEAD('src/data/europe-countries.ts') +
  `export const EUROPE_CLUB_COUNTRY: Record<string, string> = ${JSON.stringify(rekey(EUROPE_CLUB_COUNTRY, (_, v) => v), null, 2)}\n\n` +
  `export const CL_CLUB_COUNTRY: Record<string, string> = ${JSON.stringify(rekey(CL_CLUB_COUNTRY, (_, v) => v), null, 2)}\n`)

console.log(`✓ legal twins: ${Object.keys(stadiums).length}/${Object.keys(STADIUMS).length} grounds, club codes (no overrides), ` +
  `${Object.keys(rekey(EUROPE_CLUB_COUNTRY, (_, v) => v)).length + Object.keys(rekey(CL_CLUB_COUNTRY, (_, v) => v)).length} club countries`)
