/**
 * Writes src/diag/golden.ts: the engine fingerprint as Node computes it
 * (Phase 9, docs/diagnostics/04-CHECKS.md §2.3).
 *
 *   npx tsx scripts/diag-golden.ts
 *
 * Run it when you mean to change what a seed produces, after bumping
 * ENGINE_VERSION (src/engine/version.ts), and commit the file with the change.
 */
import fs from 'fs'
import path from 'path'
import { computeFingerprint } from '../src/diag/fingerprint'

const fp = computeFingerprint()
const out = `// GENERATED by scripts/diag-golden.ts — don't edit. The engine fingerprint as
// Node (V8) computes it, which the phone's self-test compares itself with.
// Regenerate only on purpose: see src/engine/version.ts.
import type { Fingerprint } from './fingerprint'

export const GOLDEN: Fingerprint = ${JSON.stringify(fp)}
`
fs.writeFileSync(path.join(__dirname, '../src/diag/golden.ts'), out)
console.log(`engine ${fp.engine} · ${fp.raw.length} seeds · ${(out.length / 1024).toFixed(0)} KB written to src/diag/golden.ts`)
