# P8-58: every country's flag as a bundled image, for RoundFlag.
# Downloads flagcdn's 80px PNGs (public-domain flag artwork) into assets/flags
# and writes src/lib/flagImages.ts, the require() map Metro needs to bundle them.
# Run from the project root:  python scripts/fetch-flags.py
import urllib.request, json, os, time

codes = json.load(urllib.request.urlopen("https://flagcdn.com/en/codes.json", timeout=30))
os.makedirs("assets/flags", exist_ok=True)
for c in sorted(codes):
    path = f"assets/flags/{c}.png"
    if os.path.exists(path):
        continue
    for _ in range(3):
        try:
            open(path, "wb").write(urllib.request.urlopen(f"https://flagcdn.com/w80/{c}.png", timeout=30).read())
            break
        except Exception:
            time.sleep(1)

have = sorted(f[:-4] for f in os.listdir("assets/flags") if f.endswith(".png"))
lines = [
    "// GENERATED by scripts/fetch-flags.py — do not edit by hand.",
    "// Every country's flag (flagcdn, 80px PNG), keyed by lower-case ISO code;",
    "// England, Scotland, Wales and Northern Ireland as gb-eng, gb-sct, gb-wls, gb-nir.",
    "/* eslint-disable */",
    "export const FLAGS: Record<string, number> = {",
] + [f"  '{c}': require('../../assets/flags/{c}.png')," for c in have] + ["}", ""]
open("src/lib/flagImages.ts", "w", encoding="utf-8", newline="\n").write("\n".join(lines))
print(len(have), "flags")
