# P8-58: every country's flag as a bundled image, for RoundFlag.
# Downloads flagcdn's PNGs (public-domain flag artwork) into assets/flags and
# writes src/lib/flagImages.ts, the require() map Metro needs to bundle them.
#
# Two sizes (P8.5-11): 80px for every small flag (chips, rows, the round
# flag), and 640px in assets/flags-large for the few places a flag fills a big
# area (the draft's player card, the globe's flag fill). The 80px one stretched
# over a whole card was the "low quality" the maintainer saw on 1 Oct; a
# single 640px set everywhere would make every tiny flag decode an image 8x
# its size. The large set is about 2.3 MB in all.
# Run from the project root:  python scripts/fetch-flags.py
import urllib.request, json, os, time

codes = json.load(urllib.request.urlopen("https://flagcdn.com/en/codes.json", timeout=30))
SETS = [("assets/flags", "w80"), ("assets/flags-large", "w640")]
for folder, width in SETS:
    os.makedirs(folder, exist_ok=True)
    for c in sorted(codes):
        path = f"{folder}/{c}.png"
        if os.path.exists(path):
            continue
        for _ in range(3):
            try:
                open(path, "wb").write(urllib.request.urlopen(f"https://flagcdn.com/{width}/{c}.png", timeout=30).read())
                break
            except Exception:
                time.sleep(1)

def entries(folder):
    have = sorted(f[:-4] for f in os.listdir(folder) if f.endswith(".png"))
    return [f"  '{c}': require('../../{folder}/{c}.png')," for c in have], len(have)

small, n_small = entries("assets/flags")
large, n_large = entries("assets/flags-large")
lines = [
    "// GENERATED by scripts/fetch-flags.py — do not edit by hand.",
    "// Every country's flag (flagcdn PNG), keyed by lower-case ISO code;",
    "// England, Scotland, Wales and Northern Ireland as gb-eng, gb-sct, gb-wls, gb-nir.",
    "// FLAGS is 80px wide, for small flags; FLAGS_LARGE is 640px, for a flag",
    "// that fills a card or a country on the globe.",
    "/* eslint-disable */",
    "export const FLAGS: Record<string, number> = {",
] + small + ["}", "", "export const FLAGS_LARGE: Record<string, number> = {"] + large + ["}", ""]
open("src/lib/flagImages.ts", "w", encoding="utf-8", newline="\n").write("\n".join(lines))
print(n_small, "flags,", n_large, "large")
