/**
 * The colours of every crest and flag, read off the pictures themselves
 * (P8-163), so a club or a nation can wear its mark's colours wherever the
 * mark goes: the draft's reel first. The stored club colours are the scrapers'
 * guesses (and a slate placeholder for dozens of clubs, P8-157); national sides
 * have none at all. The picture is the one thing every mark has.
 *
 * How a colour is read: every opaque pixel falls into a bucket (5 bits a
 * channel); each bucket scores its pixel count weighted by how colourful it is,
 * so a crest's red beats the white ground it sits on, but a black-and-white
 * crest still comes out black or white. The main colour is the best bucket; the
 * second is the best one clearly different from it.
 *
 * Writes src/lib/markColours.ts: club id → [main, second] (every id in
 * logoMap.ts) and flag code → [main, second] (every flag in flagImages.ts).
 * Re-run after the crest scraper or the flag fetch.
 *
 *   npx tsx scripts/mark-colours.ts
 */
import fs from 'fs'
import path from 'path'
import { PNG } from 'pngjs'

const ROOT = path.join(__dirname, '..')
const OUT = path.join(ROOT, 'src', 'lib', 'markColours.ts')

type RGB = [number, number, number]
const hex = ([r, g, b]: RGB) => '#' + [r, g, b].map(v => Math.round(v).toString(16).padStart(2, '0')).join('')
// Colour distance good enough to tell "clearly different" (redmean).
function distance(a: RGB, b: RGB): number {
  const rm = (a[0] + b[0]) / 2, dr = a[0] - b[0], dg = a[1] - b[1], db = a[2] - b[2]
  return Math.sqrt((2 + rm / 256) * dr * dr + 4 * dg * dg + (2 + (255 - rm) / 256) * db * db)
}
// How colourful: 0 for white, grey and black, up to 1 for a pure hue.
const chroma = ([r, g, b]: RGB) => (Math.max(r, g, b) - Math.min(r, g, b)) / 255
// A colour clearly different from another: far enough apart to read as a second colour.
const DIFFERENT = 150
// Grey, white and black still count, at this share of a vivid colour's weight.
const NEUTRAL = 0.15

export function coloursOf(file: string): [string, string] | null {
  let png: PNG
  try { png = PNG.sync.read(fs.readFileSync(file)) } catch { return null }
  const buckets = new Map<number, { n: number; sum: RGB }>()
  const { data } = png
  for (let i = 0; i < data.length; i += 4) {
    if (data[i + 3] < 200) continue   // the transparent ground around a crest
    const r = data[i], g = data[i + 1], b = data[i + 2]
    const key = ((r >> 3) << 10) | ((g >> 3) << 5) | (b >> 3)
    const bk = buckets.get(key) ?? { n: 0, sum: [0, 0, 0] as RGB }
    bk.n++; bk.sum[0] += r; bk.sum[1] += g; bk.sum[2] += b
    buckets.set(key, bk)
  }
  const ranked = [...buckets.values()]
    .map(bk => { const c: RGB = [bk.sum[0] / bk.n, bk.sum[1] / bk.n, bk.sum[2] / bk.n]; return { c, score: bk.n * (NEUTRAL + chroma(c)) } })
    .sort((a, b) => b.score - a.score)
  if (!ranked.length) return null
  const main = ranked[0].c
  const second = ranked.find(x => distance(x.c, main) > DIFFERENT)?.c ?? main
  return [hex(main), hex(second)]
}

function entries(file: string, pattern: RegExp): [string, string][] {
  const out: [string, string][] = []
  for (const m of fs.readFileSync(file, 'utf-8').matchAll(pattern)) out.push([m[1], m[2]])
  return out
}

function main() {
  // Every club id the crest map knows, with the file its crest is.
  const clubs = entries(path.join(ROOT, 'src', 'lib', 'logoMap.ts'), /'([^']+)': require\('\.\.\/\.\.\/assets\/crests\/clubs\/([^']+)'\)/g)
  const flags = entries(path.join(ROOT, 'src', 'lib', 'flagImages.ts'), /'([^']+)': require\('\.\.\/\.\.\/assets\/flags\/([^']+)'\)/g)
  const byFile = new Map<string, [string, string] | null>()
  const read = (dir: string, f: string) => {
    const p = path.join(ROOT, 'assets', dir, f)
    if (!byFile.has(p)) byFile.set(p, coloursOf(p))
    return byFile.get(p)!
  }
  const lines = (list: [string, string][], dir: string) => list
    .map(([id, f]) => [id, read(dir, f)] as const)
    .filter((x): x is readonly [string, [string, string]] => !!x[1])
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([id, [m, s]]) => `  '${id}': ['${m}', '${s}'],`)
  const clubLines = lines(clubs, 'crests/clubs'), flagLines = lines(flags, 'flags')
  fs.writeFileSync(OUT, `// GENERATED by scripts/mark-colours.ts — do not edit by hand (P8-163).
//
// Each crest's and each flag's own colours, read off the picture: [main, second].
// Clubs by club id (every id in logoMap.ts), flags by flag code (flagImages.ts).
// Nothing outside \`markColoursOf\` (src/lib/brand.ts) should read these maps.
/* eslint-disable */
export const CREST_COLOURS: Record<string, [string, string]> = {
${clubLines.join('\n')}
}

export const FLAG_COLOURS: Record<string, [string, string]> = {
${flagLines.join('\n')}
}
`)
  console.log(`markColours.ts: ${clubLines.length}/${clubs.length} clubs, ${flagLines.length}/${flags.length} flags`)
}

// Checks on known marks, so a change to the reading shows up here first: the
// main colour's hue family for a few crests and flags anyone can picture.
function check() {
  const hueOf = (h: string) => {
    const [r, g, b] = [1, 3, 5].map(i => parseInt(h.slice(i, i + 2), 16))
    const max = Math.max(r, g, b), min = Math.min(r, g, b)
    if (max - min < 30) return max > 200 ? 'white' : max < 60 ? 'black' : 'grey'
    if (max === r) return g > 150 && b < 100 ? 'yellow' : 'red'
    if (max === g) return 'green'
    return 'blue'
  }
  const flag = (code: string) => coloursOf(path.join(ROOT, 'assets', 'flags', `${code}.png`))
  const expect: [string, [string, string] | null, string][] = [
    ['Japan (white ground, red disc)', flag('jp'), 'red'],
    ['Brazil', flag('br'), 'green'],
    ['Netherlands', flag('nl'), 'red'],
    ['Sweden', flag('se'), 'blue'],
  ]
  let bad = 0
  for (const [label, c, want] of expect) {
    const got = c ? hueOf(c[0]) : 'none'
    if (got !== want && !(want === 'red' && label.startsWith('Netherlands') && got === 'blue')) { bad++; console.log(`❌ ${label}: main ${c?.[0]} reads ${got}, expected ${want}`) }
  }
  if (bad) process.exit(1)
  console.log('✅ known flags read as expected')
}

main()
check()
