/**
 * Club stadiums (P8-93).
 *
 * Every club the seeds know has its Transfermarkt `tm_id` (scrape-crests.ts
 * wrote them), and each club's stadium page is one plain page:
 *
 *   www.transfermarkt.com/-/stadion/verein/<tmId>
 *     "Name of stadium:"  → the name
 *     "Total capacity:"   → 60.704 (a dot for thousands)
 *     "Address:" rows     → the street, the postcode and city, the country
 *
 * The answers are kept in `scripts/seed/stadiums.json` (resumable: a club
 * already there is never fetched again) and written out as
 * `src/data/stadiums.ts`, keyed by the club's display NAME the way
 * `club-codes.ts` is — one real club appears under several ids (`_ucl`,
 * `_cucl`) and has one ground. It's the club's current ground, so a run in an
 * older season can show a stadium the club has since moved to (Everton,
 * Tottenham before 2019); noted in the app as "home ground".
 *
 * House rules (scrape-crests.ts, The Dugout's SCRAPE.md): resumable, a timeout
 * on every request, polite pacing, ids taken from the seeds, never guessed.
 *
 * Run: npx tsx scripts/scrape-stadiums.ts          (only what's missing)
 *      FORCE=1 npx tsx scripts/scrape-stadiums.ts   (fetch every club again)
 *      WRITE_ONLY=1 …                               (regenerate the TS file only)
 */
import fs from 'fs'
import path from 'path'
import { parse } from 'node-html-parser'
import { BASE, UA, sleep } from './lib/transfermarkt'

const SEED_DIR = path.join(__dirname, 'seed')
const CACHE = path.join(SEED_DIR, 'stadiums.json')
const OUT = path.join(__dirname, '..', 'src', 'data', 'stadiums.ts')
const FORCE = process.env.FORCE === '1'
const WRITE_ONLY = process.env.WRITE_ONLY === '1'
const PACE_MS = 1300

type Stadium = { name: string; capacity?: number; city?: string; country?: string }
type Cache = Record<string, Stadium | { missing: true }>

// Every club in every seed file with its tm_id, and the names it goes by.
function clubsFromSeeds(): Map<string, Set<string>> {
  const out = new Map<string, Set<string>>()
  for (const f of fs.readdirSync(SEED_DIR).filter(f => f.endsWith('.json') && f !== 'stadiums.json')) {
    const d = JSON.parse(fs.readFileSync(path.join(SEED_DIR, f), 'utf8'))
    const visit = (x: any) => {
      if (Array.isArray(x)) { x.forEach(visit); return }
      if (!x || typeof x !== 'object') return
      if (x.tm_id && typeof x.name === 'string' && !String(x.id ?? '').endsWith('_nt')) {
        const id = String(x.tm_id)
        out.set(id, (out.get(id) ?? new Set()).add(x.name))
      }
      for (const v of Object.values(x)) if (v && typeof v === 'object') visit(v)
    }
    visit(d)
  }
  return out
}

async function fetchText(url: string, attempt = 1): Promise<string | null> {
  try {
    const res = await fetch(url, { headers: { 'User-Agent': UA, 'Accept-Language': 'en-US,en;q=0.9' }, signal: AbortSignal.timeout(20_000) })
    if (res.status === 404) return null
    if (res.status !== 200) throw new Error(String(res.status))
    return await res.text()
  } catch (e) {
    if (attempt >= 4) { console.warn(`  gave up on ${url}: ${e}`); return null }
    await sleep(2500 * attempt)
    return fetchText(url, attempt + 1)
  }
}

const clean = (s: string) => s.replace(/&nbsp;/g, ' ').replace(/\s+/g, ' ').trim()

export function parseStadium(html: string): Stadium | null {
  const doc = parse(html)
  const rows: [string, string][] = []
  let lastTh = ''
  for (const tr of doc.querySelectorAll('tr')) {
    const th = tr.querySelector('th'), td = tr.querySelector('td')
    if (!td) continue
    const key = th ? clean(th.text) : ''
    if (key) lastTh = key
    rows.push([key || lastTh, clean(td.text)])
  }
  const get = (k: string) => rows.find(r => r[0] === k)?.[1]
  const name = get('Name of stadium:')
  if (!name) return null
  const cap = Number((get('Total capacity:') ?? '').replace(/\./g, '').replace(/[^\d]/g, ''))
  // The address runs from "Address:" down: street, postcode and city, country.
  const address = rows.filter(r => r[0] === 'Address:').map(r => r[1]).filter(Boolean)
  const country = address.length >= 2 ? address[address.length - 1] : undefined
  const cityLine = address.length >= 2 ? address[address.length - 2] : undefined
  // Drop the postcode: any word with a digit in it ("N5 1BU London" → "London").
  const city = cityLine?.split(' ').filter(w => !/\d/.test(w)).join(' ').trim() || undefined
  return { name, ...(cap ? { capacity: cap } : {}), ...(city ? { city } : {}), ...(country ? { country } : {}) }
}

function writeTs(cache: Cache, clubs: Map<string, Set<string>>) {
  const byName: Record<string, Stadium> = {}
  for (const [id, names] of clubs) {
    const s = cache[id]
    if (!s || 'missing' in s) continue
    for (const n of names) byName[n] = s
  }
  const keys = Object.keys(byName).sort()
  const body = keys.map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(byName[k])},`).join('\n')
  fs.writeFileSync(OUT, `// GENERATED by scripts/scrape-stadiums.ts (P8-93) — don't edit by hand.
// Every club's current home ground from Transfermarkt, keyed by the club's
// display name (one real club, several ids). ${keys.length} clubs.
export type Stadium = { name: string; capacity?: number; city?: string; country?: string }

export const STADIUMS: Record<string, Stadium> = {
${body}
}
`)
  console.log(`wrote ${keys.length} clubs to ${path.relative(process.cwd(), OUT)}`)
}

async function main() {
  const clubs = clubsFromSeeds()
  const cache: Cache = fs.existsSync(CACHE) ? JSON.parse(fs.readFileSync(CACHE, 'utf8')) : {}
  if (!WRITE_ONLY) {
    const todo = [...clubs.keys()].filter(id => FORCE || !cache[id])
    console.log(`${clubs.size} clubs, ${todo.length} to fetch`)
    let n = 0
    for (const id of todo) {
      const html = await fetchText(`${BASE}/-/stadion/verein/${id}`)
      const s = html ? parseStadium(html) : null
      cache[id] = s ?? { missing: true }
      if (++n % 20 === 0 || n === todo.length) {
        fs.writeFileSync(CACHE, JSON.stringify(cache, null, 1))
        console.log(`  ${n}/${todo.length}  last: ${[...clubs.get(id)!][0]} → ${s?.name ?? 'none'}`)
      }
      await sleep(PACE_MS)
    }
    fs.writeFileSync(CACHE, JSON.stringify(cache, null, 1))
  }
  writeTs(cache, clubs)
}

// Only when run, not when a check imports parseStadium.
if (require.main === module) main().catch(e => { console.error(e); process.exit(1) })
