// GENERATED by scripts/build-legal-twins.ts from scripts/legal-names/clubs.csv —
// don't edit by hand. The public build's twin of src/data/club-codes.ts (metro.config.js swaps it in).
/* eslint-disable */
// Three-letter club codes for ClubTag (a code on the club's colour tape —
// clubs are typographic in Kit Drop, never crests).
//
// The database already carries `clubs.short_name`, but it's the first three
// letters of a word, which gave 54 clashes INSIDE a single competition (both
// Manchester clubs were MAN, PSG was SAI next to Saint-Étienne's SAI). The DB
// code stays the base; this table overrides every clash, plus the few clubs
// whose code is known well enough that anything else reads wrong (PSG, BVB).
//
// Keyed by display NAME, not id: the same club appears under several ids
// (`psv_eindhoven_ucl`, …) and must carry one code everywhere.
// `npx tsx scripts/verify-club-codes.ts` fails if any competition has a clash.

export const CLUB_CODE_OVERRIDES: Record<string, string> = {}

// Letters only, diacritics folded, first three — the fallback when neither the
// table nor the database has a code.
function derive(name: string): string {
  const letters = name.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^A-Za-z0-9]/g, '')
  return (letters.slice(0, 3) || '???').toUpperCase()
}

export function clubCode(name: string, dbShortName?: string | null): string {
  return CLUB_CODE_OVERRIDES[name] ?? (dbShortName ? dbShortName.toUpperCase() : derive(name))
}
