// GENERATED by scripts/build-legal-twins.ts from scripts/legal-names/clubs.csv —
// don't edit by hand. The public build's twin of src/data/stadiums.ts (metro.config.js swaps it in).
/* eslint-disable */
export type Stadium = { name: string; capacity?: number; city?: string; country?: string }

export const STADIUMS: Record<string, Stadium> = {
  "Vestur Black": {
    "name": "Vestur Black Ground",
    "capacity": 2000
  },
  "Heidenheim Red": {
    "name": "Heidenheim an der Brenz Stadium",
    "capacity": 10001,
    "city": "Heidenheim an der Brenz",
    "country": "Germany"
  },
  "Köln Red": {
    "name": "Müngersdorf Stadium",
    "capacity": 46195,
    "city": "Müngersdorf",
    "country": "Germany"
  },
  "Nuremberg Claret": {
    "name": "Nuremberg Stadium",
    "capacity": 50000,
    "city": "Nuremberg",
    "country": "Germany"
  },
  "Slovacko Navy": {
    "name": "Uherské Hradiště Stadium",
    "capacity": 8121,
    "city": "Uherské Hradiště",
    "country": "Czech Republic"
  },
  "Berlin Red": {
    "name": "Treptow-Köpenick Stadium",
    "capacity": 21704,
    "city": "Treptow-Köpenick",
    "country": "Germany"
  },
  "Mainz Red": {
    "name": "Mainz Stadium",
    "capacity": 34034,
    "city": "Mainz",
    "country": "Germany"
  },
  "Ajaccio Sky": {
    "name": "Ajaccio Stadium",
    "capacity": 10660,
    "city": "Ajaccio",
    "country": "France"
  },
  "Juvenes-Dogana Red": {
    "name": "Serravalle Stadium",
    "capacity": 6664,
    "city": "Serravalle",
    "country": "San Marino"
  },
  "Libertas Claret": {
    "name": "Borgo Maggiore Stadium",
    "capacity": 1000,
    "city": "Borgo Maggiore",
    "country": "San Marino"
  },
  "Milan Black": {
    "name": "Milan Stadium",
    "capacity": 75817,
    "city": "Milan",
    "country": "Italy"
  },
  "Monza Red": {
    "name": "Monza Stadium",
    "capacity": 17102,
    "city": "Monza",
    "country": "Italy"
  },
  "Oulu Navy": {
    "name": "Oulu Stadium",
    "capacity": 9000,
    "city": "Oulu",
    "country": "Finland"
  },
  "Prague Claret": {
    "name": "Bubeneč Stadium",
    "capacity": 19416,
    "city": "Bubeneč",
    "country": "Czech Republic"
  },
  "Acquaviva Green": {
    "name": "Acquaviva Stadium",
    "city": "Acquaviva",
    "country": "San Marino"
  },
  "Fiorentina Purple": {
    "name": "Florence Stadium",
    "capacity": 43325,
    "city": "Florence",
    "country": "Italy"
  },
  "Arges Purple": {
    "name": "Pitești Stadium",
    "capacity": 15000,
    "city": "Pitești",
    "country": "Romania"
  },
  "Kifisia Navy": {
    "name": "Athens Municipality Stadium",
    "capacity": 16003,
    "city": "Athens Municipality",
    "country": "Greece"
  },
  "Larisa Claret": {
    "name": "Larissa Municipality Stadium",
    "capacity": 17118,
    "city": "Larissa Municipality",
    "country": "Greece"
  },
  "Athens Yellow": {
    "name": "Nea Filadelfeia-Nea Chalkidona Municipality Stadium",
    "capacity": 31100,
    "city": "Nea Filadelfeia-Nea Chalkidona Municipality",
    "country": "Greece"
  },
  "Larnaca Yellow": {
    "name": "Larnaca Stadium",
    "capacity": 7380,
    "city": "Larnaca",
    "country": "Cyprus"
  },
  "Limassol Yellow": {
    "name": "Kolossi Stadium",
    "capacity": 10300,
    "city": "Kolossi",
    "country": "Cyprus"
  },
  "Elbasani Yellow": {
    "name": "Elbasani Yellow Ground",
    "capacity": 12800
  },
  "Bournemouth Black": {
    "name": "Bournemouth Stadium",
    "capacity": 12000,
    "city": "Bournemouth",
    "country": "United Kingdom"
  },
  "Slobozia Blue": {
    "name": "Slobozia Stadium",
    "capacity": 6000,
    "city": "Slobozia",
    "country": "Romania"
  },
  "Sweden Black": {
    "name": "Solna Municipality Stadium",
    "capacity": 54329,
    "city": "Solna Municipality",
    "country": "Sweden"
  },
  "Auxerre Black": {
    "name": "Auxerre Stadium",
    "capacity": 18541,
    "city": "Auxerre",
    "country": "France"
  },
  "Strumica Green": {
    "name": "Strumica Stadium",
    "capacity": 6500,
    "city": "Strumica",
    "country": "North Macedonia"
  },
  "Nicosia Yellow": {
    "name": "Strovolos Stadium",
    "capacity": 22709,
    "city": "Strovolos",
    "country": "Cyprus"
  },
  "Monaco Red": {
    "name": "Fontvieille Stadium",
    "capacity": 18523,
    "city": "Fontvieille",
    "country": "Monaco"
  },
  "Roma Claret": {
    "name": "Rome Stadium",
    "capacity": 70634,
    "city": "Rome",
    "country": "Italy"
  },
  "Saint-Étienne Green": {
    "name": "Saint-Étienne Stadium",
    "capacity": 41965,
    "city": "Saint-Étienne",
    "country": "France"
  },
  "Trencin Red": {
    "name": "Trenčín Stadium",
    "capacity": 4300,
    "city": "Trenčín",
    "country": "Slovakia"
  },
  "Alkmaar Red": {
    "name": "Alkmaar Stadium",
    "capacity": 17023,
    "city": "Alkmaar",
    "country": "Netherlands"
  },
  "GF Navy": {
    "name": "Aarhus Municipality Stadium",
    "capacity": 19433,
    "city": "Aarhus Municipality",
    "country": "Denmark"
  },
  "Aberdeen Red": {
    "name": "Aberdeen City Stadium",
    "capacity": 21421,
    "city": "Aberdeen City",
    "country": "United Kingdom"
  },
  "Amsterdam Black": {
    "name": "Amsterdam Stadium",
    "capacity": 54990,
    "city": "Amsterdam",
    "country": "Netherlands"
  },
  "Chloraka Green": {
    "name": "Chloraka Stadium",
    "capacity": 3500,
    "city": "Chloraka",
    "country": "Cyprus"
  },
  "Turkey Orange": {
    "name": "Alanya Stadium",
    "city": "Alanya",
    "country": "Turkey"
  },
  "Yerevan Blue": {
    "name": "Shengavit District Stadium",
    "capacity": 6800,
    "city": "Shengavit District",
    "country": "Armenia"
  },
  "Amiens Black": {
    "name": "Amiens Stadium",
    "capacity": 12097,
    "city": "Amiens",
    "country": "France"
  },
  "SCO Black": {
    "name": "Angers Stadium",
    "capacity": 18000,
    "city": "Angers",
    "country": "France"
  },
  "Famagusta Blue": {
    "name": "Larnaca Stadium",
    "capacity": 9781,
    "city": "Larnaca",
    "country": "Cyprus"
  },
  "Turkey Black": {
    "name": "Antalya Stadium",
    "capacity": 7100,
    "city": "Antalya",
    "country": "Turkey"
  },
  "Limassol Blue": {
    "name": "Kolossi Stadium",
    "capacity": 10300,
    "city": "Kolossi",
    "country": "Cyprus"
  },
  "Azerbaijan Red": {
    "name": "Nakhchivan Stadium",
    "capacity": 12800,
    "city": "Nakhchivan",
    "country": "Azerbaijan"
  },
  "Kardzhali Sky": {
    "name": "Kardzhali Stadium",
    "capacity": 10000,
    "city": "Kardzhali",
    "country": "Bulgaria"
  },
  "Limassol Green": {
    "name": "Kolossi Stadium",
    "capacity": 10300,
    "city": "Kolossi",
    "country": "Cyprus"
  },
  "Thessaloniki Yellow": {
    "name": "Thessaloniki Municipality Stadium",
    "capacity": 22800,
    "city": "Thessaloniki Municipality",
    "country": "Greece"
  },
  "Gdynia Yellow": {
    "name": "Gdynia Stadium",
    "capacity": 15139,
    "city": "Gdynia",
    "country": "Poland"
  },
  "Bielefeld Blue": {
    "name": "Bielefeld Stadium",
    "capacity": 27300,
    "city": "Bielefeld",
    "country": "Germany"
  },
  "Dzerzhinsk Red": {
    "name": "Barysaŭ District Stadium",
    "capacity": 5402,
    "city": "Barysaŭ District",
    "country": "Belarus"
  },
  "England Red": {
    "name": "London Borough of Islington Stadium",
    "capacity": 60338,
    "city": "London Borough of Islington",
    "country": "United Kingdom"
  },
  "Tivat Blue": {
    "name": "Tivat Blue Ground",
    "country": "Montenegro"
  },
  "North Macedonia Yellow": {
    "name": "North Macedonia Yellow Ground",
    "capacity": 4000
  },
  "Aktor Yellow": {
    "name": "Tripoli Municipality Stadium",
    "capacity": 7616,
    "city": "Tripoli Municipality",
    "country": "Greece"
  },
  "Villa Claret": {
    "name": "Birmingham Stadium",
    "capacity": 42640,
    "city": "Birmingham",
    "country": "United Kingdom"
  },
  "BC Blue": {
    "name": "Bergamo Stadium",
    "capacity": 24950,
    "city": "Bergamo",
    "country": "Italy"
  },
  "Bilbao Black": {
    "name": "Bilbao Stadium",
    "capacity": 53289,
    "city": "Bilbao",
    "country": "Spain"
  },
  "d'Escaldes Blue": {
    "name": "Andorra la Vella Stadium",
    "city": "Andorra la Vella",
    "country": "Andorra"
  },
  "Madrid Red": {
    "name": "Madrid Stadium",
    "capacity": 70813,
    "city": "Madrid",
    "country": "Spain"
  },
  "Athens Navy": {
    "name": "Municipality of Peristeri Stadium",
    "capacity": 10200,
    "city": "Municipality of Peristeri",
    "country": "Greece"
  },
  "Vienna Purple": {
    "name": "Vienna Stadium",
    "capacity": 17656,
    "city": "Vienna",
    "country": "Austria"
  },
  "Futebol Red": {
    "name": "Futebol Red Ground",
    "capacity": 6230
  },
  "Tórshavn Black": {
    "name": "Tórshavn Municipality Stadium",
    "capacity": 5000,
    "city": "Tórshavn Municipality",
    "country": "Faroe Islands"
  },
  "Toftir Red": {
    "name": "Nes Municipality Stadium",
    "capacity": 6000,
    "city": "Nes Municipality",
    "country": "Faroe Islands"
  },
  "Borisov Yellow": {
    "name": "Barysaŭ District Stadium",
    "capacity": 13121,
    "city": "Barysaŭ District",
    "country": "Belarus"
  },
  "Daugavpils Blue": {
    "name": "Daugavpils Blue Ground",
    "capacity": 5000,
    "country": "Latvia"
  },
  "Häcken Yellow": {
    "name": "Gothenburg Municipality Stadium",
    "capacity": 7000,
    "city": "Gothenburg Municipality",
    "country": "Sweden"
  },
  "Yerevan Navy": {
    "name": "Yerevan Navy Ground",
    "capacity": 1428
  },
  "Boys Yellow": {
    "name": "Bern Stadium",
    "capacity": 32000,
    "city": "Bern",
    "country": "Switzerland"
  },
  "Bala Black": {
    "name": "Bala Stadium",
    "capacity": 3000,
    "city": "Bala",
    "country": "United Kingdom"
  },
  "Ballymena Sky": {
    "name": "Ballymena Stadium",
    "capacity": 4100,
    "city": "Ballymena",
    "country": "United Kingdom"
  },
  "Bangor Yellow": {
    "name": "Bangor Yellow Ground",
    "capacity": 1900500
  },
  "Barry Yellow": {
    "name": "Barry Yellow Ground",
    "country": "United Kingdom"
  },
  "Basaksehir Orange": {
    "name": "Başakşehir Stadium",
    "capacity": 80597,
    "city": "Başakşehir",
    "country": "Turkey"
  },
  "North Macedonia Black": {
    "name": "North Macedonia Black Ground",
    "capacity": 3000,
    "country": "North Macedonia"
  },
  "Leverkusen Black": {
    "name": "Leverkusen Stadium",
    "capacity": 30210,
    "city": "Leverkusen",
    "country": "Germany"
  },
  "Munich Red": {
    "name": "Schwabing-Freimann Stadium",
    "capacity": 75024,
    "city": "Schwabing-Freimann",
    "country": "Germany"
  },
  "Jerusalem Yellow": {
    "name": "Jerusalem Stadium",
    "capacity": 31733,
    "city": "Jerusalem",
    "country": "Israel"
  },
  "Benevento Yellow": {
    "name": "Benevento Stadium",
    "capacity": 25000,
    "city": "Benevento",
    "country": "Italy"
  },
  "Bulgaria Green": {
    "name": "Stara Zagora Stadium",
    "capacity": 12128,
    "city": "Stara Zagora",
    "country": "Bulgaria"
  },
  "JK Black": {
    "name": "Beşiktaş Stadium",
    "capacity": 41903,
    "city": "Beşiktaş",
    "country": "Turkey"
  },
  "Birkirkara Red": {
    "name": "Ta' Qali Stadium",
    "capacity": 17797,
    "city": "Ta' Qali",
    "country": "Malta"
  },
  "Bohemian Red": {
    "name": "Phibsborough Stadium",
    "capacity": 7955,
    "city": "Phibsborough",
    "country": "Ireland"
  },
  "Prague Green": {
    "name": "Vršovice Stadium",
    "capacity": 7500,
    "city": "Vršovice",
    "country": "Czech Republic"
  },
  "Bologna Navy": {
    "name": "Bologna Stadium",
    "capacity": 36462,
    "city": "Bologna",
    "country": "Italy"
  },
  "Dortmund Yellow": {
    "name": "Dortmund Stadium",
    "capacity": 81359,
    "city": "Dortmund",
    "country": "Germany"
  },
  "Mönchengladbach Black": {
    "name": "Mönchengladbach Stadium",
    "capacity": 59749,
    "city": "Mönchengladbach",
    "country": "Germany"
  },
  "Plovdiv Black": {
    "name": "Plovdiv Stadium",
    "capacity": 18000,
    "city": "Plovdiv",
    "country": "Bulgaria"
  },
  "Vratsa Green": {
    "name": "Vratsa Stadium",
    "city": "Vratsa",
    "country": "Bulgaria"
  },
  "Kópavogur Green": {
    "name": "Kópavogur Stadium",
    "capacity": 5501,
    "city": "Kópavogur",
    "country": "Iceland"
  },
  "Brentford Black": {
    "name": "Brentford Stadium",
    "capacity": 14863,
    "city": "Brentford",
    "country": "United Kingdom"
  },
  "Brescia Blue": {
    "name": "Brescia Stadium",
    "capacity": 16308,
    "city": "Brescia",
    "country": "Italy"
  },
  "Hove Blue": {
    "name": "Moulsecoomb and Bevendean Stadium",
    "capacity": 31800,
    "city": "Moulsecoomb and Bevendean",
    "country": "United Kingdom"
  },
  "Llansawel Red": {
    "name": "Llansawel Red Ground",
    "capacity": 2000
  },
  "Bruk-Bet Orange": {
    "name": "Gmina Żabno Stadium",
    "capacity": 4666,
    "city": "Gmina Żabno",
    "country": "Poland"
  },
  "Bryne Red": {
    "name": "Bryne Stadium",
    "capacity": 10000,
    "city": "Bryne",
    "country": "Norway"
  },
  "Bröndby Blue": {
    "name": "Brøndby Municipality Stadium",
    "capacity": 29000,
    "city": "Brøndby Municipality",
    "country": "Denmark"
  },
  "Podgorica Blue": {
    "name": "Podgorica Stadium",
    "capacity": 12000,
    "city": "Podgorica",
    "country": "Montenegro"
  },
  "Burnley Blue": {
    "name": "Burnley Stadium",
    "capacity": 22546,
    "city": "Burnley",
    "country": "United Kingdom"
  },
  "Osasuna Gold": {
    "name": "Pamplona Stadium",
    "capacity": 23576,
    "city": "Pamplona",
    "country": "Spain"
  },
  "Leganés Black": {
    "name": "Leganés Stadium",
    "capacity": 11454,
    "city": "Leganés",
    "country": "Spain"
  },
  "Nacional Black": {
    "name": "Madeira Stadium",
    "capacity": 5200,
    "city": "Madeira",
    "country": "Portugal"
  },
  "Clara Red": {
    "name": "Ponta Delgada Stadium",
    "capacity": 12500,
    "city": "Ponta Delgada",
    "country": "Portugal"
  },
  "Tondela Green": {
    "name": "Tondela Stadium",
    "capacity": 5000,
    "city": "Tondela",
    "country": "Portugal"
  },
  "d'Andorra Black": {
    "name": "d'Andorra Black Ground"
  },
  "Amadora Black": {
    "name": "Amadora Stadium",
    "capacity": 9288,
    "city": "Amadora",
    "country": "Portugal"
  },
  "Cluj Claret": {
    "name": "Cluj-Napoca Stadium",
    "capacity": 23500,
    "city": "Cluj-Napoca",
    "country": "Romania"
  },
  "Selemet Red": {
    "name": "Selemet Red Ground",
    "capacity": 150
  },
  "Bulgaria Red": {
    "name": "Bulgaria Red Ground",
    "country": "Bulgaria"
  },
  "Sofia Red": {
    "name": "Stolichna Municipality Stadium",
    "capacity": 22015,
    "city": "Stolichna Municipality",
    "country": "Bulgaria"
  },
  "Caernarfon Yellow": {
    "name": "Caernarfon Stadium",
    "capacity": 3000,
    "city": "Caernarfon",
    "country": "United Kingdom"
  },
  "Cagliari Navy": {
    "name": "Cagliari Stadium",
    "capacity": 16416,
    "city": "Cagliari",
    "country": "Italy"
  },
  "Cardiff Blue": {
    "name": "Cardiff Stadium",
    "capacity": 33260,
    "city": "Cardiff",
    "country": "United Kingdom"
  },
  "University Claret": {
    "name": "University Claret Ground",
    "capacity": 1620510
  },
  "Carrick Yellow": {
    "name": "Carrick Yellow Ground",
    "capacity": 1500
  },
  "Pia Black": {
    "name": "Pia Black Ground",
    "capacity": 6000
  },
  "Rizespor Blue": {
    "name": "Rize Stadium",
    "capacity": 15558,
    "city": "Rize",
    "country": "Turkey"
  },
  "Vigo Red": {
    "name": "Vigo Stadium",
    "capacity": 24870,
    "city": "Vigo",
    "country": "Spain"
  },
  "Scotland Navy": {
    "name": "Vigo Stadium",
    "capacity": 24870,
    "city": "Vigo",
    "country": "Spain"
  },
  "Brugge Green": {
    "name": "Bruges Stadium",
    "capacity": 29062,
    "city": "Bruges",
    "country": "Belgium"
  },
  "Chelsea Blue": {
    "name": "Fulham Stadium",
    "capacity": 41875,
    "city": "Fulham",
    "country": "United Kingdom"
  },
  "Varna Green": {
    "name": "Varna Stadium",
    "capacity": 8250,
    "city": "Varna",
    "country": "Bulgaria"
  },
  "Verona Yellow": {
    "name": "Verona Stadium",
    "capacity": 31045,
    "city": "Verona",
    "country": "Italy"
  },
  "Foot Navy": {
    "name": "Clermont-Ferrand Stadium",
    "capacity": 11980,
    "city": "Clermont-Ferrand",
    "country": "France"
  },
  "Cliftonville Red": {
    "name": "Belfast Stadium",
    "capacity": 2530,
    "city": "Belfast",
    "country": "United Kingdom"
  },
  "Brugge Black": {
    "name": "Bruges Stadium",
    "capacity": 29062,
    "city": "Bruges",
    "country": "Belgium"
  },
  "Carroi Red": {
    "name": "Carroi Red Ground",
    "capacity": 2000
  },
  "Coleraine Blue": {
    "name": "Coleraine Stadium",
    "capacity": 13132,
    "city": "Coleraine",
    "country": "United Kingdom"
  },
  "Bay Claret": {
    "name": "Bay Claret Ground",
    "capacity": 3000
  },
  "Como Blue": {
    "name": "Como Stadium",
    "capacity": 13602,
    "city": "Como",
    "country": "Italy"
  },
  "Nomads Red": {
    "name": "Connah's Quay Stadium",
    "capacity": 420,
    "city": "Connah's Quay",
    "country": "United Kingdom"
  },
  "F.C. Green": {
    "name": "Turners Cross Stadium",
    "capacity": 7485,
    "city": "Turners Cross",
    "country": "Ireland"
  },
  "Poland Black": {
    "name": "Kraków Stadium",
    "capacity": 15016,
    "city": "Kraków",
    "country": "Poland"
  },
  "Crusaders Red": {
    "name": "Belfast Stadium",
    "capacity": 3383,
    "city": "Belfast",
    "country": "United Kingdom"
  },
  "Palace Black": {
    "name": "South Norwood Stadium",
    "capacity": 26255,
    "city": "South Norwood",
    "country": "United Kingdom"
  },
  "Cádiz Yellow": {
    "name": "Cádiz Stadium",
    "capacity": 26000,
    "city": "Cádiz",
    "country": "Spain"
  },
  "Streda Yellow": {
    "name": "Dunajská Streda Stadium",
    "capacity": 16410,
    "city": "Dunajská Streda",
    "country": "Slovakia"
  },
  "Dainava Red": {
    "name": "Dainava Red Ground",
    "capacity": 3748,
    "country": "Lithuania"
  },
  "Buiucani Blue": {
    "name": "Buiucani Blue Ground",
    "capacity": 5200
  },
  "VSC Red": {
    "name": "Debrecen Stadium",
    "capacity": 10200,
    "city": "Debrecen",
    "country": "Hungary"
  },
  "Degerfors Red": {
    "name": "Degerfors Municipality Stadium",
    "capacity": 12500,
    "city": "Degerfors Municipality",
    "country": "Sweden"
  },
  "Alavés Black": {
    "name": "Vitoria-Gasteiz Stadium",
    "capacity": 19840,
    "city": "Vitoria-Gasteiz",
    "country": "Spain"
  },
  "Derry Red": {
    "name": "Derry City and Strabane Stadium",
    "capacity": 6300,
    "city": "Derry City and Strabane",
    "country": "Northern Ireland"
  },
  "FCO Red": {
    "name": "Dijon Stadium",
    "capacity": 15995,
    "city": "Dijon",
    "country": "France"
  },
  "Batumi Blue": {
    "name": "Kobuleti Stadium",
    "capacity": 6000,
    "city": "Kobuleti",
    "country": "Georgia"
  },
  "Minsk Black": {
    "name": "Minsk Stadium",
    "capacity": 22000,
    "city": "Minsk",
    "country": "Belarus"
  },
  "Tbilisi Blue": {
    "name": "Tbilisi Stadium",
    "capacity": 54549,
    "city": "Tbilisi",
    "country": "Georgia"
  },
  "VTK Red": {
    "name": "Diósgyőr Stadium",
    "capacity": 14655,
    "city": "Diósgyőr",
    "country": "Hungary"
  },
  "Djurgårdens Navy": {
    "name": "Stockholm Municipality Stadium",
    "capacity": 30001,
    "city": "Stockholm Municipality",
    "country": "Sweden"
  },
  "Bulgaria Yellow": {
    "name": "Dobrich Stadium",
    "capacity": 12500,
    "city": "Dobrich",
    "country": "Bulgaria"
  },
  "Drogheda Claret": {
    "name": "Drogheda Stadium",
    "capacity": 2000,
    "city": "Drogheda",
    "country": "Ireland"
  },
  "Dundee Navy": {
    "name": "Dundee City Stadium",
    "capacity": 11506,
    "city": "Dundee City",
    "country": "United Kingdom"
  },
  "Dundee Orange": {
    "name": "Dundee City Stadium",
    "capacity": 14229,
    "city": "Dundee City",
    "country": "United Kingdom"
  },
  "Swifts Blue": {
    "name": "Dungannon Stadium",
    "capacity": 5000,
    "city": "Dungannon",
    "country": "United Kingdom"
  },
  "Brest Blue": {
    "name": "Brest Region Stadium",
    "capacity": 10169,
    "city": "Brest Region",
    "country": "Belarus"
  },
  "Kyiv Blue": {
    "name": "Kyiv Stadium",
    "capacity": 70050,
    "city": "Kyiv",
    "country": "Ukraine"
  },
  "Guingamp Red": {
    "name": "Guingamp Stadium",
    "capacity": 18250,
    "city": "Guingamp",
    "country": "France"
  },
  "Faroe Islands Black": {
    "name": "Sunda Municipality Stadium",
    "capacity": 1500,
    "city": "Sunda Municipality",
    "country": "Faroe Islands"
  },
  "Troyes Blue": {
    "name": "Troyes Stadium",
    "capacity": 20400,
    "city": "Troyes",
    "country": "France"
  },
  "ETO Green": {
    "name": "Győr Stadium",
    "capacity": 16000,
    "city": "Győr",
    "country": "Hungary"
  },
  "Frankfurt Black": {
    "name": "Frankfurt-Süd Stadium",
    "capacity": 51500,
    "city": "Frankfurt-Süd",
    "country": "Germany"
  },
  "Elche Green": {
    "name": "Elche Stadium",
    "capacity": 31388,
    "city": "Elche",
    "country": "Spain"
  },
  "Paralimni Sky": {
    "name": "Paralimni Stadium",
    "capacity": 4532,
    "city": "Paralimni",
    "country": "Cyprus"
  },
  "Epicentr Grey": {
    "name": "Kamianets-Podilskyi Stadium",
    "capacity": 2587,
    "city": "Kamianets-Podilskyi",
    "country": "Ukraine"
  },
  "Achna Navy": {
    "name": "Achna Stadium",
    "capacity": 5367,
    "city": "Achna",
    "country": "Cyprus"
  },
  "Europa Green": {
    "name": "Gibraltar Stadium",
    "capacity": 5000,
    "city": "Gibraltar",
    "country": "United Kingdom"
  },
  "Point Navy": {
    "name": "Gibraltar Stadium",
    "capacity": 5000,
    "city": "Gibraltar",
    "country": "United Kingdom"
  },
  "Everton Blue": {
    "name": "City of Liverpool Stadium",
    "capacity": 52769,
    "city": "City of Liverpool",
    "country": "United Kingdom"
  },
  "Rotterdam Black": {
    "name": "Rotterdam Stadium",
    "capacity": 3531,
    "city": "Rotterdam",
    "country": "Netherlands"
  },
  "Turkey Yellow": {
    "name": "Turkey Yellow Ground",
    "capacity": 14234
  },
  "Dudelange Yellow": {
    "name": "Dudelange Stadium",
    "capacity": 4650,
    "city": "Dudelange",
    "country": "Luxembourg"
  },
  "Siauliai Black": {
    "name": "Siauliai Black Ground",
    "capacity": 3030
  },
  "Aktobe Red": {
    "name": "Aktobe Stadium",
    "capacity": 12800,
    "city": "Aktobe",
    "country": "Kazakhstan"
  },
  "Alverca Blue": {
    "name": "Alverca Blue Ground",
    "capacity": 6932
  },
  "Yerevan Red": {
    "name": "Kentron District Stadium",
    "capacity": 14403,
    "city": "Kentron District",
    "country": "Armenia"
  },
  "Ararat-Armenia Black": {
    "name": "Avan District Stadium",
    "capacity": 1500,
    "city": "Avan District",
    "country": "Armenia"
  },
  "Arouca Yellow": {
    "name": "Arouca Stadium",
    "capacity": 5600,
    "city": "Arouca",
    "country": "Portugal"
  },
  "Ashdod Red": {
    "name": "Ashdod Stadium",
    "capacity": 7800,
    "city": "Ashdod",
    "country": "Israel"
  },
  "Astana Yellow": {
    "name": "Astana Stadium",
    "capacity": 30000,
    "city": "Astana",
    "country": "Kazakhstan"
  },
  "Bissen Yellow": {
    "name": "Bissen Yellow Ground",
    "capacity": 1500
  },
  "Atyrau Green": {
    "name": "Atyrau Stadium",
    "capacity": 8660,
    "city": "Atyrau",
    "country": "Kazakhstan"
  },
  "Augsburg Claret": {
    "name": "Augsburg Stadium",
    "capacity": 30660,
    "city": "Augsburg",
    "country": "Germany"
  },
  "Ballkani Orange": {
    "name": "Ballkani Orange Ground",
    "capacity": 3000
  },
  "Balti Blue": {
    "name": "Bălți Stadium",
    "capacity": 5953,
    "city": "Bălți",
    "country": "Moldova"
  },
  "Ostrava Blue": {
    "name": "Slezská Ostrava Stadium",
    "capacity": 17372,
    "city": "Slezská Ostrava",
    "country": "Czech Republic"
  },
  "Barcelona Navy": {
    "name": "La Maternitat i Sant Ramon Stadium",
    "capacity": 105000,
    "city": "La Maternitat i Sant Ramon",
    "country": "Spain"
  },
  "Basel Blue": {
    "name": "Bad Cannstatt Stadium",
    "capacity": 60058,
    "city": "Bad Cannstatt",
    "country": "Germany"
  },
  "Blau-Weiss Blue": {
    "name": "Linz Stadium",
    "city": "Linz",
    "country": "Austria"
  },
  "Botosani Red": {
    "name": "Botoșani Stadium",
    "capacity": 12000,
    "city": "Botoșani",
    "country": "Romania"
  },
  "Magpies Black": {
    "name": "Gibraltar Stadium",
    "capacity": 5000,
    "city": "Gibraltar",
    "country": "United Kingdom"
  },
  "College Black": {
    "name": "Gibraltar Stadium",
    "capacity": 5000,
    "city": "Gibraltar",
    "country": "United Kingdom"
  },
  "Copenhagen Black": {
    "name": "Copenhagen Municipality Stadium",
    "capacity": 38065,
    "city": "Copenhagen Municipality",
    "country": "Denmark"
  },
  "Crotone Navy": {
    "name": "Crotone Stadium",
    "capacity": 16640,
    "city": "Crotone",
    "country": "Italy"
  },
  "Differdange Red": {
    "name": "Differdange Stadium",
    "capacity": 1800,
    "city": "Differdange",
    "country": "Luxembourg"
  },
  "Gori Red": {
    "name": "Gori Stadium",
    "capacity": 5000,
    "city": "Gori",
    "country": "Georgia"
  },
  "Romania Red": {
    "name": "Sector 2 Stadium",
    "capacity": 55634,
    "city": "Sector 2",
    "country": "Romania"
  },
  "Albania Sky": {
    "name": "Tirana Stadium",
    "capacity": 12500,
    "city": "Tirana",
    "country": "Albania"
  },
  "Domagnano Red": {
    "name": "Domagnano Stadium",
    "capacity": 500,
    "city": "Domagnano",
    "country": "San Marino"
  },
  "Drenica Red": {
    "name": "Drenica Red Ground",
    "country": "Kosovo"
  },
  "Drita Blue": {
    "name": "Drita Blue Ground",
    "capacity": 15000,
    "country": "Kosovo"
  },
  "Telšiai Claret": {
    "name": "Telšiai Claret Ground",
    "capacity": 2400
  },
  "Empoli Blue": {
    "name": "Empoli Stadium",
    "capacity": 19847,
    "city": "Empoli",
    "country": "Italy"
  },
  "Famalicão Navy": {
    "name": "Vila Nova de Famalicão Stadium",
    "capacity": 5186,
    "city": "Vila Nova de Famalicão",
    "country": "Portugal"
  },
  "Ferizaj Blue": {
    "name": "Ferizaj Blue Ground",
    "capacity": 3000
  },
  "Fiorentino Navy": {
    "name": "Fiorentino Stadium",
    "capacity": 700,
    "city": "Fiorentino",
    "country": "San Marino"
  },
  "Tallinn Green": {
    "name": "Tallinn Stadium",
    "capacity": 14336,
    "city": "Tallinn",
    "country": "Estonia"
  },
  "Fredericia Red": {
    "name": "Fredericia Municipality Stadium",
    "capacity": 4000,
    "city": "Fredericia Municipality",
    "country": "Denmark"
  },
  "Gagra Blue": {
    "name": "Gagra Blue Ground",
    "capacity": 2500
  },
  "Sagarejo Black": {
    "name": "Sagarejo Black Ground",
    "capacity": 2000
  },
  "Bordeaux Navy": {
    "name": "Bordeaux Stadium",
    "capacity": 42566,
    "city": "Bordeaux",
    "country": "France"
  },
  "Groningen Black": {
    "name": "Groningen Stadium",
    "capacity": 22550,
    "city": "Groningen",
    "country": "Netherlands"
  },
  "Haka Black": {
    "name": "Valkeakoski Stadium",
    "capacity": 3516,
    "city": "Valkeakoski",
    "country": "Finland"
  },
  "Hegelmann Blue": {
    "name": "Hegelmann Blue Ground",
    "capacity": 1550
  },
  "Hermannstadt Red": {
    "name": "Sibiu Stadium",
    "capacity": 14200,
    "city": "Sibiu",
    "country": "Romania"
  },
  "Kralove Black": {
    "name": "Malšovice Stadium",
    "capacity": 9300,
    "city": "Malšovice",
    "country": "Czech Republic"
  },
  "Imishli Green": {
    "name": "Imishli Green Ground",
    "capacity": 8500
  },
  "Turku Blue": {
    "name": "Turku Stadium",
    "capacity": 9372,
    "city": "Turku",
    "country": "Finland"
  },
  "Canach Navy": {
    "name": "Canach Stadium",
    "capacity": 1000,
    "city": "Canach",
    "country": "Luxembourg"
  },
  "Kharkiv Claret": {
    "name": "Kharkiv Stadium",
    "capacity": 40003,
    "city": "Kharkiv",
    "country": "Ukraine"
  },
  "Kolkheti-1913 Blue": {
    "name": "Poti Stadium",
    "capacity": 6000,
    "city": "Poti",
    "country": "Georgia"
  },
  "Koper Yellow": {
    "name": "Koper Stadium",
    "capacity": 4047,
    "city": "Koper",
    "country": "Slovenia"
  },
  "Kosice Yellow": {
    "name": "Košice-Juh Stadium",
    "capacity": 12555,
    "city": "Košice-Juh",
    "country": "Slovakia"
  },
  "Kudrivka Blue": {
    "name": "Kudrivka Blue Ground",
    "capacity": 500
  },
  "Kuressaare Yellow": {
    "name": "Saaremaa Rural Municipality Stadium",
    "capacity": 1000,
    "city": "Saaremaa Rural Municipality",
    "country": "Estonia"
  },
  "Kyzylzhar Red": {
    "name": "Petropavl Stadium",
    "capacity": 11000,
    "city": "Petropavl",
    "country": "Kazakhstan"
  },
  "Lausanne-Sport Blue": {
    "name": "Canton of Vaud Stadium",
    "capacity": 50000,
    "city": "Canton of Vaud",
    "country": "Switzerland"
  },
  "Lorient Orange": {
    "name": "Lorient Stadium",
    "capacity": 19010,
    "city": "Lorient",
    "country": "France"
  },
  "Lugano Black": {
    "name": "Canton of Ticino Stadium",
    "capacity": 8093,
    "city": "Canton of Ticino",
    "country": "Switzerland"
  },
  "Luzern Navy": {
    "name": "Canton of Lucerne Stadium",
    "capacity": 16800,
    "city": "Canton of Lucerne",
    "country": "Switzerland"
  },
  "Malisheva Blue": {
    "name": "Malisheva Blue Ground",
    "capacity": 1800
  },
  "Mamer Red": {
    "name": "Mamer Red Ground",
    "country": "Luxembourg"
  },
  "Bucharest Orange": {
    "name": "Sector 2 Stadium",
    "city": "Sector 2",
    "country": "Romania"
  },
  "Metz Claret": {
    "name": "Longeville-lès-Metz Stadium",
    "capacity": 26671,
    "city": "Longeville-lès-Metz",
    "country": "France"
  },
  "Midtjylland Black": {
    "name": "Herning Municipality Stadium",
    "capacity": 11809,
    "city": "Herning Municipality",
    "country": "Denmark"
  },
  "Orhei Red": {
    "name": "Orhei Stadium",
    "capacity": 2539,
    "city": "Orhei",
    "country": "Moldova"
  },
  "Nantes Yellow": {
    "name": "Nantes Stadium",
    "capacity": 35318,
    "city": "Nantes",
    "country": "France"
  },
  "Yerevan Navy & White": {
    "name": "Yerevan Stadium",
    "capacity": 7000,
    "city": "Yerevan",
    "country": "Armenia"
  },
  "Nordsjaelland Red": {
    "name": "Furesø Municipality Stadium",
    "capacity": 10100,
    "city": "Furesø Municipality",
    "country": "Denmark"
  },
  "Oleksandriya Yellow": {
    "name": "Oleksandriia Stadium",
    "capacity": 7000,
    "city": "Oleksandriia",
    "country": "Ukraine"
  },
  "Ordino Orange": {
    "name": "Aixovall Stadium",
    "capacity": 1000,
    "city": "Aixovall",
    "country": "Andorra"
  },
  "Hincesti Black": {
    "name": "Hîncești Stadium",
    "city": "Hîncești",
    "country": "Moldova"
  },
  "Porto Blue": {
    "name": "Campanhã Stadium",
    "capacity": 50033,
    "city": "Campanhã",
    "country": "Portugal"
  },
  "Prishtina Blue": {
    "name": "Pristina Stadium",
    "capacity": 16200,
    "city": "Pristina",
    "country": "Kosovo"
  },
  "Niederkorn Black": {
    "name": "Niederkorn Stadium",
    "capacity": 4830,
    "city": "Niederkorn",
    "country": "Luxembourg"
  },
  "Yerevan Claret": {
    "name": "Avan District Stadium",
    "capacity": 1500,
    "city": "Avan District",
    "country": "Armenia"
  },
  "RFS Blue": {
    "name": "RFS Blue Ground",
    "capacity": 2300,
    "country": "Latvia"
  },
  "Rapid Claret": {
    "name": "Bucharest Stadium",
    "capacity": 14000,
    "city": "Bucharest",
    "country": "Romania"
  },
  "Rodange Red": {
    "name": "Rodange Red Ground"
  },
  "Rànger's Yellow": {
    "name": "Aixovall Stadium",
    "capacity": 1000,
    "city": "Aixovall",
    "country": "Andorra"
  },
  "Tskaltubo Green": {
    "name": "Tskaltubo Green Ground",
    "capacity": 3500
  },
  "Coloma Black": {
    "name": "Aixovall Stadium",
    "capacity": 1000,
    "city": "Aixovall",
    "country": "Andorra"
  },
  "Schalke Blue": {
    "name": "Gelsenkirchen-Nord Stadium",
    "capacity": 62271,
    "city": "Gelsenkirchen-Nord",
    "country": "Germany"
  },
  "Shamakhi Navy": {
    "name": "Baku Stadium",
    "capacity": 8125,
    "city": "Baku",
    "country": "Azerbaijan"
  },
  "Tiraspol Yellow": {
    "name": "Tiraspol Stadium",
    "capacity": 14300,
    "city": "Tiraspol",
    "country": "Moldova"
  },
  "Gyumri Black": {
    "name": "Gyumri Stadium",
    "capacity": 2761,
    "city": "Gyumri",
    "country": "Armenia"
  },
  "Shkupi Blue": {
    "name": "Čair Stadium",
    "city": "Čair",
    "country": "North Macedonia"
  },
  "Sion Red": {
    "name": "Canton of Valais Stadium",
    "capacity": 16263,
    "city": "Canton of Valais",
    "country": "Switzerland"
  },
  "Liberec Black": {
    "name": "Liberec Stadium",
    "capacity": 9900,
    "city": "Liberec",
    "country": "Czech Republic"
  },
  "Sluck Blue": {
    "name": "Slutsk Stadium",
    "capacity": 1896,
    "city": "Slutsk",
    "country": "Belarus"
  },
  "Smarhoń Red": {
    "name": "Smarhon Stadium",
    "capacity": 3500,
    "city": "Smarhon",
    "country": "Belarus"
  },
  "Gallen Green": {
    "name": "Canton of St. Gallen Stadium",
    "capacity": 19694,
    "city": "Canton of St. Gallen",
    "country": "Switzerland"
  },
  "Pauli Red": {
    "name": "Hamburg-Mitte Stadium",
    "capacity": 29546,
    "city": "Hamburg-Mitte",
    "country": "Germany"
  },
  "Suðuroy Blue": {
    "name": "Suðuroy Blue Ground",
    "capacity": 3000,
    "country": "Faroe Islands"
  },
  "Presov Green": {
    "name": "Prešov Stadium",
    "capacity": 5410,
    "city": "Prešov",
    "country": "Slovakia"
  },
  "Telavi Blue": {
    "name": "Telavi Blue Ground",
    "capacity": 12000
  },
  "Thun Red": {
    "name": "Canton of Berne Stadium",
    "capacity": 10000,
    "city": "Canton of Berne",
    "country": "Switzerland"
  },
  "Toulouse Purple": {
    "name": "Toulouse Stadium",
    "capacity": 33150,
    "city": "Toulouse",
    "country": "France"
  },
  "Turan Blue": {
    "name": "Turkistan Stadium",
    "city": "Turkistan",
    "country": "Kazakhstan"
  },
  "Enschede Red": {
    "name": "Enschede Stadium",
    "capacity": 30000,
    "city": "Enschede",
    "country": "Netherlands"
  },
  "Strassen Red": {
    "name": "Strassen Red Ground"
  },
  "Zhezkazgan Blue": {
    "name": "Zhezkazgan Blue Ground",
    "capacity": 2500
  },
  "Cluj Black": {
    "name": "Cluj-Napoca Stadium",
    "capacity": 30335,
    "city": "Cluj-Napoca",
    "country": "Romania"
  },
  "Yerevan Yellow": {
    "name": "Malatia-Sebastia District Stadium",
    "capacity": 5000,
    "city": "Malatia-Sebastia District",
    "country": "Armenia"
  },
  "Utrecht Red": {
    "name": "Utrecht Stadium",
    "capacity": 23750,
    "city": "Utrecht",
    "country": "Netherlands"
  },
  "Van Navy": {
    "name": "Van Navy Ground",
    "capacity": 5000
  },
  "Rosport Red": {
    "name": "Rosport Red Ground",
    "country": "Luxembourg"
  },
  "Plzen Red": {
    "name": "Východní Předměstí Stadium",
    "capacity": 11700,
    "city": "Východní Předměstí",
    "country": "Czech Republic"
  },
  "Volendam Orange": {
    "name": "Edam-Volendam Stadium",
    "capacity": 6200,
    "city": "Edam-Volendam",
    "country": "Netherlands"
  },
  "Winterthur Red": {
    "name": "Neuwiesen Stadium",
    "capacity": 8700,
    "city": "Neuwiesen",
    "country": "Switzerland"
  },
  "Molodechno Grey": {
    "name": "Maladziečna District Stadium",
    "capacity": 4560,
    "city": "Maladziečna District",
    "country": "Belarus"
  },
  "Chisinau Yellow": {
    "name": "Sectorul Botanica Stadium",
    "capacity": 10400,
    "city": "Sectorul Botanica",
    "country": "Moldova"
  },
  "Zlin Yellow": {
    "name": "Zlín Stadium",
    "capacity": 6375,
    "city": "Zlín",
    "country": "Czech Republic"
  },
  "Zürich Navy": {
    "name": "Canton of Zurich Stadium",
    "capacity": 25000,
    "city": "Canton of Zurich",
    "country": "Switzerland"
  },
  "Levadia Green": {
    "name": "Tallinn Stadium",
    "capacity": 14336,
    "city": "Tallinn",
    "country": "Estonia"
  },
  "Romania Blue": {
    "name": "Hamburg-Mitte Stadium",
    "capacity": 29546,
    "city": "Hamburg-Mitte",
    "country": "Germany"
  },
  "EH Blue": {
    "name": "Denderleeuw Stadium",
    "capacity": 12000,
    "city": "Denderleeuw",
    "country": "Belgium"
  },
  "Constanta Blue": {
    "name": "Constanța Stadium",
    "capacity": 15500,
    "city": "Constanța",
    "country": "Romania"
  },
  "Jaro Red": {
    "name": "Jakobstad Stadium",
    "capacity": 7000,
    "city": "Jakobstad",
    "country": "Finland"
  },
  "Hafnarfjördur Black": {
    "name": "Hafnarfjördur Black Ground",
    "capacity": 6500305
  },
  "Auda Green": {
    "name": "Auda Green Ground",
    "capacity": 7000
  },
  "Gargzdai Orange": {
    "name": "Gargždai Stadium",
    "capacity": 2000,
    "city": "Gargždai",
    "country": "Lithuania"
  },
  "Bodø/Glimt Yellow": {
    "name": "Bodø Municipality Stadium",
    "capacity": 7354,
    "city": "Bodø Municipality",
    "country": "Norway"
  },
  "Bokelj Blue": {
    "name": "Kotor Stadium",
    "capacity": 5000,
    "city": "Kotor",
    "country": "Montenegro"
  },
  "Luka Blue": {
    "name": "Banja Luka Stadium",
    "capacity": 9730,
    "city": "Banja Luka",
    "country": "Bosnia and Herzegovina"
  },
  "Bylis Red": {
    "name": "Ballsh Stadium",
    "capacity": 5200,
    "city": "Ballsh",
    "country": "Albania"
  },
  "Ciuc Red": {
    "name": "Miercurea Ciuc Stadium",
    "city": "Miercurea Ciuc",
    "country": "Romania"
  },
  "Cukaricki Black": {
    "name": "Čukarica City Municipality Stadium",
    "capacity": 4070,
    "city": "Čukarica City Municipality",
    "country": "Serbia"
  },
  "Tuzi Red": {
    "name": "Tuzi Stadium",
    "capacity": 1000,
    "city": "Tuzi",
    "country": "Montenegro"
  },
  "Prague Claret & Yellow": {
    "name": "Prague 6 Stadium",
    "capacity": 8150,
    "city": "Prague 6",
    "country": "Czech Republic"
  },
  "Gabala Red": {
    "name": "Qabala Stadium",
    "capacity": 4000,
    "city": "Qabala",
    "country": "Azerbaijan"
  },
  "Gomel Green": {
    "name": "Gomel Region Stadium",
    "capacity": 14307,
    "city": "Gomel Region",
    "country": "Belarus"
  },
  "Grobina Blue": {
    "name": "Grobina Blue Ground",
    "capacity": 200
  },
  "Belgrad Red": {
    "name": "Belgrad Red Ground",
    "capacity": 8030
  },
  "Jablonec Green": {
    "name": "Jablonec nad Nisou Stadium",
    "capacity": 6280,
    "city": "Jablonec nad Nisou",
    "country": "Czech Republic"
  },
  "Javor-Matis Red": {
    "name": "Ivanjica Stadium",
    "capacity": 5000,
    "city": "Ivanjica",
    "country": "Serbia"
  },
  "Jezero Blue": {
    "name": "Plav Stadium",
    "capacity": 5000,
    "city": "Plav",
    "country": "Montenegro"
  },
  "Zalgiris Green": {
    "name": "Kaunas Stadium",
    "capacity": 15315,
    "city": "Kaunas",
    "country": "Lithuania"
  },
  "Liepaja Black": {
    "name": "Liepāja Stadium",
    "capacity": 5008,
    "city": "Liepāja",
    "country": "Latvia"
  },
  "Metta Green": {
    "name": "Metta Green Ground",
    "capacity": 500
  },
  "Minsk Red": {
    "name": "Minsk Stadium",
    "capacity": 3000,
    "city": "Minsk",
    "country": "Belarus"
  },
  "Boleslav Blue": {
    "name": "Mladá Boleslav II Stadium",
    "capacity": 5000,
    "city": "Mladá Boleslav II",
    "country": "Czech Republic"
  },
  "Gorica Red": {
    "name": "Gorica Red Ground",
    "capacity": 4300
  },
  "Lucani Blue": {
    "name": "Lucanians Stadium",
    "capacity": 8000,
    "city": "Lucanians",
    "country": "Serbia"
  },
  "Bar Blue": {
    "name": "Bar Stadium",
    "capacity": 6000,
    "city": "Bar",
    "country": "Montenegro"
  },
  "Krusevac Red": {
    "name": "Kruševac Stadium",
    "capacity": 10331,
    "city": "Kruševac",
    "country": "Serbia"
  },
  "Pazar Blue": {
    "name": "Novi Pazar Stadium",
    "capacity": 12000,
    "city": "Novi Pazar",
    "country": "Serbia"
  },
  "Panevezys Red": {
    "name": "Panevėžys Stadium",
    "capacity": 4000,
    "city": "Panevėžys",
    "country": "Lithuania"
  },
  "Pardubice Red": {
    "name": "Pardubice Red Ground",
    "capacity": 2500,
    "country": "Czech Republic"
  },
  "Belgrade Red": {
    "name": "Belgrade Stadium",
    "capacity": 32710,
    "city": "Belgrade",
    "country": "Serbia"
  },
  "Partizani Red": {
    "name": "Tirana Stadium",
    "capacity": 12500,
    "city": "Tirana",
    "country": "Albania"
  },
  "Kragujevac Red": {
    "name": "Kragujevac Stadium",
    "capacity": 15100,
    "city": "Kragujevac",
    "country": "Serbia"
  },
  "Nis Red": {
    "name": "Niš Stadium",
    "capacity": 18151,
    "city": "Niš",
    "country": "Serbia"
  },
  "Bijeljina Blue": {
    "name": "Bijeljina Stadium",
    "capacity": 6000,
    "city": "Bijeljina",
    "country": "Bosnia and Herzegovina"
  },
  "Surdulica Blue": {
    "name": "Surdulica Stadium",
    "capacity": 3312,
    "city": "Surdulica",
    "country": "Serbia"
  },
  "Prijedor Yellow": {
    "name": "Prijedor Stadium",
    "capacity": 6000,
    "city": "Prijedor",
    "country": "Bosnia and Herzegovina"
  },
  "Sarajevo Claret": {
    "name": "Centar Municipality Stadium",
    "capacity": 30121,
    "city": "Centar Municipality",
    "country": "Bosnia and Herzegovina"
  },
  "Meridian Red": {
    "name": "Meridian Red Ground",
    "capacity": 3000
  },
  "Subotica Navy": {
    "name": "Subotica Stadium",
    "capacity": 13000,
    "city": "Subotica",
    "country": "Serbia"
  },
  "Marijampole Red": {
    "name": "Marijampolė Stadium",
    "capacity": 6250,
    "city": "Marijampolė",
    "country": "Lithuania"
  },
  "Niksic Blue": {
    "name": "Nikšić Stadium",
    "capacity": 5214,
    "city": "Nikšić",
    "country": "Montenegro"
  },
  "Topola Black": {
    "name": "Topola Black Ground",
    "capacity": 4500
  },
  "Teplice Yellow": {
    "name": "Teplice Stadium",
    "capacity": 17087,
    "city": "Teplice",
    "country": "Czech Republic"
  },
  "Trakai Yellow": {
    "name": "Vilnius Stadium",
    "capacity": 5067,
    "city": "Vilnius",
    "country": "Lithuania"
  },
  "Tukums Green": {
    "name": "Tukums Green Ground"
  },
  "Mostar Red": {
    "name": "City of Mostar Stadium",
    "capacity": 7000,
    "city": "City of Mostar",
    "country": "Bosnia and Herzegovina"
  },
  "Vitebsk Yellow": {
    "name": "Vitebsk Yellow Ground",
    "capacity": 8144
  },
  "Sad Red": {
    "name": "Novi Sad Stadium",
    "capacity": 14458,
    "city": "Novi Sad",
    "country": "Serbia"
  },
  "Vilnius Black": {
    "name": "Vilnius Stadium",
    "capacity": 5067,
    "city": "Vilnius",
    "country": "Lithuania"
  },
  "Pancevo Navy": {
    "name": "Pancevo Navy Ground",
    "capacity": 2967
  },
  "Sarajevo Blue": {
    "name": "Grbavica Stadium",
    "capacity": 16100,
    "city": "Grbavica",
    "country": "Bosnia and Herzegovina"
  },
  "Jelgava Claret": {
    "name": "Jelgava Stadium",
    "capacity": 1560,
    "city": "Jelgava",
    "country": "Latvia"
  },
  "Falkirk Navy": {
    "name": "Falkirk Stadium",
    "capacity": 8750,
    "city": "Falkirk",
    "country": "United Kingdom"
  },
  "Karagümrük Red": {
    "name": "Başakşehir Stadium",
    "capacity": 80597,
    "city": "Başakşehir",
    "country": "Turkey"
  },
  "Turkey Yellow & Navy": {
    "name": "Kadıköy Stadium",
    "capacity": 50530,
    "city": "Kadıköy",
    "country": "Turkey"
  },
  "TC Black": {
    "name": "Manchester Stadium",
    "capacity": 52900,
    "city": "Manchester",
    "country": "United Kingdom"
  },
  "Rotterdam Red": {
    "name": "Rotterdam Stadium",
    "capacity": 51577,
    "city": "Rotterdam",
    "country": "Netherlands"
  },
  "Flamurtari Black": {
    "name": "Vlorë Stadium",
    "capacity": 13000,
    "city": "Vlorë",
    "country": "Albania"
  },
  "Flint Black": {
    "name": "Flint Black Ground",
    "capacity": 1000250
  },
  "Floriana Green": {
    "name": "Ta' Qali Stadium",
    "capacity": 17797,
    "city": "Ta' Qali",
    "country": "Malta"
  },
  "Düsseldorf Red": {
    "name": "Stockum Stadium",
    "capacity": 66500,
    "city": "Stockum",
    "country": "Germany"
  },
  "Sittard Yellow": {
    "name": "Sittard-Geleen Stadium",
    "capacity": 12500,
    "city": "Sittard-Geleen",
    "country": "Netherlands"
  },
  "Haugesund Blue": {
    "name": "Haugesund Municipality Stadium",
    "capacity": 8800,
    "city": "Haugesund Municipality",
    "country": "Norway"
  },
  "Reykjavík Blue": {
    "name": "Laugardalur Stadium",
    "capacity": 15427,
    "city": "Laugardalur",
    "country": "Iceland"
  },
  "Fredrikstad Red": {
    "name": "Fredrikstad Municipality Stadium",
    "capacity": 12560,
    "city": "Fredrikstad Municipality",
    "country": "Norway"
  },
  "Frosinone Yellow": {
    "name": "Frosinone Stadium",
    "capacity": 16227,
    "city": "Frosinone",
    "country": "Italy"
  },
  "Fulham Black": {
    "name": "Fulham Stadium",
    "capacity": 25700,
    "city": "Fulham",
    "country": "United Kingdom"
  },
  "Sweden Black & White": {
    "name": "Gothenburg Municipality Stadium",
    "capacity": 18416,
    "city": "Gothenburg Municipality",
    "country": "Sweden"
  },
  "Praia Yellow": {
    "name": "Cascais e Estoril Stadium",
    "capacity": 5094,
    "city": "Cascais e Estoril",
    "country": "Portugal"
  },
  "Katowice Yellow": {
    "name": "Zaleska Halda-Brynow Stadium",
    "capacity": 15048,
    "city": "Zaleska Halda-Brynow",
    "country": "Poland"
  },
  "Zagreb Blue": {
    "name": "Sector 2 Stadium",
    "capacity": 55634,
    "city": "Sector 2",
    "country": "Romania"
  },
  "Turkey Navy": {
    "name": "Sarıyer Stadium",
    "capacity": 52652,
    "city": "Sarıyer",
    "country": "Turkey"
  },
  "Galway Claret": {
    "name": "Galway Stadium",
    "capacity": 5000,
    "city": "Galway",
    "country": "Ireland"
  },
  "Kapan Navy": {
    "name": "Kapan Stadium",
    "capacity": 3500,
    "city": "Kapan",
    "country": "Armenia"
  },
  "Gaziantep Red": {
    "name": "Şehitkâmil district Stadium",
    "capacity": 33502,
    "city": "Şehitkâmil district",
    "country": "Turkey"
  },
  "Ankara Black": {
    "name": "Eryaman Stadium",
    "city": "Eryaman",
    "country": "Turkey"
  },
  "Italy Navy": {
    "name": "Genoa Stadium",
    "capacity": 33205,
    "city": "Genoa",
    "country": "Italy"
  },
  "Getafe Blue": {
    "name": "Getafe Stadium",
    "capacity": 16500,
    "city": "Getafe",
    "country": "Spain"
  },
  "Vicente Red": {
    "name": "Freguesia de Vila Boa Stadium",
    "capacity": 12046,
    "city": "Freguesia de Vila Boa",
    "country": "Portugal"
  },
  "Girona Blue": {
    "name": "Girona Stadium",
    "capacity": 14624,
    "city": "Girona",
    "country": "Spain"
  },
  "Glacis Claret": {
    "name": "Gibraltar Stadium",
    "capacity": 5000,
    "city": "Gibraltar",
    "country": "United Kingdom"
  },
  "Glenavon Blue": {
    "name": "Lurgan Stadium",
    "capacity": 4160,
    "city": "Lurgan",
    "country": "United Kingdom"
  },
  "Glentoran Green": {
    "name": "Belfast Stadium",
    "capacity": 26556,
    "city": "Belfast",
    "country": "United Kingdom"
  },
  "Eagles Red": {
    "name": "South Norwood Stadium",
    "capacity": 26255,
    "city": "South Norwood",
    "country": "United Kingdom"
  },
  "Granada Red": {
    "name": "Granada Stadium",
    "capacity": 19436,
    "city": "Granada",
    "country": "Spain"
  },
  "Zurich Black": {
    "name": "Canton of Zurich Stadium",
    "capacity": 25000,
    "city": "Canton of Zurich",
    "country": "Switzerland"
  },
  "AK Red": {
    "name": "Liebenau Stadium",
    "capacity": 15400,
    "city": "Liebenau",
    "country": "Austria"
  },
  "Gzira Claret": {
    "name": "Ta' Qali Stadium",
    "capacity": 17797,
    "city": "Ta' Qali",
    "country": "Malta"
  },
  "Zabrze Black": {
    "name": "Zabrze Stadium",
    "capacity": 28499,
    "city": "Zabrze",
    "country": "Poland"
  },
  "Turkey Yellow & Red": {
    "name": "Konak Stadium",
    "capacity": 70000,
    "city": "Konak",
    "country": "Turkey"
  },
  "Tórshavn Red": {
    "name": "Tórshavn Municipality Stadium",
    "capacity": 5000,
    "city": "Tórshavn Municipality",
    "country": "Faroe Islands"
  },
  "Helsinki Blue": {
    "name": "Helsinki Stadium",
    "capacity": 10770,
    "city": "Helsinki",
    "country": "Finland"
  },
  "Gorica Gold": {
    "name": "Maksimir Stadium",
    "capacity": 60000,
    "city": "Maksimir",
    "country": "Croatia"
  },
  "Split Blue": {
    "name": "Split Stadium",
    "capacity": 35000,
    "city": "Split",
    "country": "Croatia"
  },
  "Rijeka Gold": {
    "name": "Rijeka Stadium",
    "capacity": 12600,
    "city": "Rijeka",
    "country": "Croatia"
  },
  "Vukovar Sky": {
    "name": "Vukovar Sky Ground",
    "capacity": 6000
  },
  "Posusje Sky": {
    "name": "Posušje Stadium",
    "capacity": 8000,
    "city": "Posušje",
    "country": "Bosnia and Herzegovina"
  },
  "Mostar Black": {
    "name": "City of Mostar Stadium",
    "capacity": 9000,
    "city": "City of Mostar",
    "country": "Bosnia and Herzegovina"
  },
  "Halmstads Blue": {
    "name": "Halmstads Blue Ground",
    "capacity": 10873
  },
  "Norway Green": {
    "name": "Hamar Municipality Stadium",
    "capacity": 7600,
    "city": "Hamar Municipality",
    "country": "Norway"
  },
  "Hamburger Red": {
    "name": "Altona Stadium",
    "capacity": 57000,
    "city": "Altona",
    "country": "Germany"
  },
  "Hammarby Green": {
    "name": "Stockholm Municipality Stadium",
    "capacity": 30001,
    "city": "Stockholm Municipality",
    "country": "Sweden"
  },
  "Spartans Black": {
    "name": "Ħamrun Stadium",
    "capacity": 1962,
    "city": "Ħamrun",
    "country": "Malta"
  },
  "Hannover Black": {
    "name": "Mitte Stadium",
    "capacity": 49000,
    "city": "Mitte",
    "country": "Germany"
  },
  "Sheva Red": {
    "name": "Beersheba Stadium",
    "capacity": 16126,
    "city": "Beersheba",
    "country": "Israel"
  },
  "Haifa Red": {
    "name": "Haifa Stadium",
    "capacity": 30950,
    "city": "Haifa",
    "country": "Israel"
  },
  "Jerusalem Red": {
    "name": "Jerusalem Stadium",
    "capacity": 31733,
    "city": "Jerusalem",
    "country": "Israel"
  },
  "Tikva Blue": {
    "name": "Petah Tikva Stadium",
    "capacity": 11500,
    "city": "Petah Tikva",
    "country": "Israel"
  },
  "Aviv Red": {
    "name": "Tel Aviv Stadium",
    "capacity": 29400,
    "city": "Tel Aviv",
    "country": "Israel"
  },
  "Laagri Red": {
    "name": "Laagri Red Ground",
    "capacity": 500
  },
  "County Blue": {
    "name": "County Blue Ground",
    "country": "United Kingdom"
  },
  "Midlothian Claret": {
    "name": "City of Edinburgh Stadium",
    "capacity": 17529,
    "city": "City of Edinburgh",
    "country": "United Kingdom"
  },
  "Verona Navy": {
    "name": "Verona Stadium",
    "capacity": 31045,
    "city": "Verona",
    "country": "Italy"
  },
  "Almelo Black": {
    "name": "Almelo Stadium",
    "capacity": 12080,
    "city": "Almelo",
    "country": "Netherlands"
  },
  "Hertha Black": {
    "name": "Charlottenburg-Wilmersdorf Stadium",
    "capacity": 74475,
    "city": "Charlottenburg-Wilmersdorf",
    "country": "Germany"
  },
  "Hibernian Green": {
    "name": "City of Edinburgh Stadium",
    "capacity": 20421,
    "city": "City of Edinburgh",
    "country": "United Kingdom"
  },
  "Hibernians Black": {
    "name": "Paola Stadium",
    "capacity": 2000,
    "city": "Paola",
    "country": "Malta"
  },
  "Kiel Blue": {
    "name": "Kiel Stadium",
    "capacity": 15034,
    "city": "Kiel",
    "country": "Germany"
  },
  "Huddersfield Blue": {
    "name": "Kirklees Stadium",
    "capacity": 24500,
    "city": "Kirklees",
    "country": "United Kingdom"
  },
  "Brommapojkarna Red": {
    "name": "Stockholm Municipality Stadium",
    "capacity": 4729,
    "city": "Stockholm Municipality",
    "country": "Sweden"
  },
  "Elfsborg Yellow": {
    "name": "Borås Municipality Stadium",
    "capacity": 16200,
    "city": "Borås Municipality",
    "country": "Sweden"
  },
  "Gnistan Yellow": {
    "name": "Helsinki Stadium",
    "capacity": 2200,
    "city": "Helsinki",
    "country": "Finland"
  },
  "Göteborg Blue": {
    "name": "Gothenburg Municipality Stadium",
    "capacity": 18416,
    "city": "Gothenburg Municipality",
    "country": "Sweden"
  },
  "Mariehamn Green": {
    "name": "Mariehamn Stadium",
    "capacity": 4000,
    "city": "Mariehamn",
    "country": "Finland"
  },
  "Värnamo Blue": {
    "name": "Värnamo Municipality Stadium",
    "capacity": 5000,
    "city": "Värnamo Municipality",
    "country": "Sweden"
  },
  "Sirius Blue": {
    "name": "Uppsala Municipality Stadium",
    "capacity": 6500,
    "city": "Uppsala Municipality",
    "country": "Sweden"
  },
  "Tbilisi Red": {
    "name": "Tbilisi Stadium",
    "capacity": 27223,
    "city": "Tbilisi",
    "country": "Georgia"
  },
  "Norrköping Blue": {
    "name": "Norrköping Blue Ground",
    "capacity": 16000
  },
  "Sakhnin Red": {
    "name": "Sakhnin Stadium",
    "capacity": 8500,
    "city": "Sakhnin",
    "country": "Israel"
  },
  "Tampere Yellow": {
    "name": "Tampere Stadium",
    "capacity": 3100,
    "city": "Tampere",
    "country": "Finland"
  },
  "d'Escaldes Blue & Black": {
    "name": "Andorra la Vella Stadium",
    "city": "Andorra la Vella",
    "country": "Andorra"
  },
  "Milan Black & White": {
    "name": "Milan Stadium",
    "capacity": 75817,
    "city": "Milan",
    "country": "Italy"
  },
  "Ipswich Blue": {
    "name": "Ipswich Stadium",
    "capacity": 30311,
    "city": "Ipswich",
    "country": "United Kingdom"
  },
  "Shmona Blue": {
    "name": "Kiryat Shmona Stadium",
    "capacity": 5300,
    "city": "Kiryat Shmona",
    "country": "Israel"
  },
  "Tiberias Blue": {
    "name": "Tiberias Stadium",
    "city": "Tiberias",
    "country": "Israel"
  },
  "Region Blue": {
    "name": "Minsk Stadium",
    "capacity": 3000,
    "city": "Minsk",
    "country": "Belarus"
  },
  "Tallinn Black": {
    "name": "Tallinn Stadium",
    "capacity": 12000,
    "city": "Tallinn",
    "country": "Estonia"
  },
  "Narva Red": {
    "name": "Narva City Stadium",
    "capacity": 1065,
    "city": "Narva City",
    "country": "Estonia"
  },
  "Bialystok Yellow": {
    "name": "Białystok Stadium",
    "capacity": 22372,
    "city": "Białystok",
    "country": "Poland"
  },
  "Tammeka Blue": {
    "name": "Tartu City Stadium",
    "capacity": 1600,
    "city": "Tartu City",
    "country": "Estonia"
  },
  "Polje Blue": {
    "name": "Bijelo Polje Stadium",
    "capacity": 5000,
    "city": "Bijelo Polje",
    "country": "Montenegro"
  },
  "Esch Black": {
    "name": "Esch-sur-Alzette Stadium",
    "capacity": 4000,
    "city": "Esch-sur-Alzette",
    "country": "Luxembourg"
  },
  "Italy Black": {
    "name": "Turin Stadium",
    "capacity": 41689,
    "city": "Turin",
    "country": "Italy"
  },
  "Akureyri Yellow": {
    "name": "Akureyri Stadium",
    "capacity": 2000,
    "city": "Akureyri",
    "country": "Iceland"
  },
  "Gent Blue": {
    "name": "Ghent Stadium",
    "capacity": 12919,
    "city": "Ghent",
    "country": "Belgium"
  },
  "Dukagjini Black": {
    "name": "Dukagjini Black Ground",
    "capacity": 3000
  },
  "Egnatia Green": {
    "name": "Egnatia Green Ground",
    "country": "Albania"
  },
  "Llapi Blue": {
    "name": "Llapi Blue Ground",
    "capacity": 2000,
    "country": "Kosovo"
  },
  "Re Blue": {
    "name": "Re Blue Ground",
    "capacity": 4000
  },
  "Teuta Blue": {
    "name": "Durrës Stadium",
    "capacity": 12040,
    "city": "Durrës",
    "country": "Albania"
  },
  "Tirana Blue": {
    "name": "Tirana Stadium",
    "capacity": 12500,
    "city": "Tirana",
    "country": "Albania"
  },
  "Vllaznia Red": {
    "name": "Shkodër Stadium",
    "capacity": 16000,
    "city": "Shkodër",
    "country": "Albania"
  },
  "Vora Red": {
    "name": "Vora Red Ground",
    "capacity": 3200
  },
  "Komarno Purple": {
    "name": "Komarno Purple Ground",
    "capacity": 4408500
  },
  "KFUM-Kameratene Red": {
    "name": "Oslo Stadium",
    "city": "Oslo",
    "country": "Norway"
  },
  "Reykjavík Black": {
    "name": "Vesturbær Stadium",
    "capacity": 2781,
    "city": "Vesturbær",
    "country": "Iceland"
  },
  "Genk Blue": {
    "name": "Genk Stadium",
    "capacity": 25000,
    "city": "Genk",
    "country": "Belgium"
  },
  "Mechelen Yellow": {
    "name": "Mechelen Stadium",
    "capacity": 13213,
    "city": "Mechelen",
    "country": "Belgium"
  },
  "Westerlo Yellow": {
    "name": "Westerlo Stadium",
    "capacity": 7982,
    "city": "Westerlo",
    "country": "Belgium"
  },
  "Almaty Yellow": {
    "name": "Almaty Stadium",
    "capacity": 23804,
    "city": "Almaty",
    "country": "Kazakhstan"
  },
  "Kalju Black": {
    "name": "Tallinn Stadium",
    "capacity": 650,
    "city": "Tallinn",
    "country": "Estonia"
  },
  "PFK Yellow": {
    "name": "Ganja Stadium",
    "capacity": 25000,
    "city": "Ganja",
    "country": "Azerbaijan"
  },
  "Lviv Green": {
    "name": "Lviv Stadium",
    "capacity": 28051,
    "city": "Lviv",
    "country": "Ukraine"
  },
  "Yevlakh Red": {
    "name": "Yevlakh Stadium",
    "capacity": 5000,
    "city": "Yevlakh",
    "country": "Azerbaijan"
  },
  "Turkey Blue": {
    "name": "Kasımpaşa Stadium",
    "capacity": 14234,
    "city": "Kasımpaşa",
    "country": "Turkey"
  },
  "Kyzylorda Red": {
    "name": "Kyzylorda Stadium",
    "capacity": 7300,
    "city": "Kyzylorda",
    "country": "Kazakhstan"
  },
  "Turkey Red": {
    "name": "Kayseri Stadium",
    "capacity": 32864,
    "city": "Kayseri",
    "country": "Turkey"
  },
  "Kilmarnock Navy": {
    "name": "East Ayrshire Stadium",
    "capacity": 18128,
    "city": "East Ayrshire",
    "country": "United Kingdom"
  },
  "Kisvárda Red": {
    "name": "Kisvárda Red Ground",
    "capacity": 2750
  },
  "Turkey Green": {
    "name": "İzmit Stadium",
    "city": "İzmit",
    "country": "Turkey"
  },
  "Kovalivka Navy": {
    "name": "Kovalivka Stadium",
    "city": "Kovalivka",
    "country": "Ukraine"
  },
  "Turkey Green & White": {
    "name": "Selçuklu Stadium",
    "capacity": 42276,
    "city": "Selçuklu",
    "country": "Turkey"
  },
  "Kielce Yellow": {
    "name": "Kielce Stadium",
    "capacity": 15500,
    "city": "Kielce",
    "country": "Poland"
  },
  "Palloilijat Green": {
    "name": "Kotka Stadium",
    "capacity": 4780,
    "city": "Kotka",
    "country": "Finland"
  },
  "ENY Green": {
    "name": "Ypsonas Stadium",
    "city": "Ypsonas",
    "country": "Cyprus"
  },
  "Kristiansund Navy": {
    "name": "Kristiansund Navy Ground",
    "capacity": 4444
  },
  "Rig Red": {
    "name": "Kryvyi Rih Stadium",
    "capacity": 2500,
    "city": "Kryvyi Rih",
    "country": "Ukraine"
  },
  "Palloseura Yellow": {
    "name": "Kuopio Stadium",
    "capacity": 2700,
    "city": "Kuopio",
    "country": "Finland"
  },
  "Klaksvík Blue": {
    "name": "Klaksvík Blue Ground",
    "capacity": 3000,
    "country": "Faroe Islands"
  },
  "Austria Yellow": {
    "name": "Linz Stadium",
    "capacity": 18000,
    "city": "Linz",
    "country": "Austria"
  },
  "Cherkasy Purple": {
    "name": "Cherkasy Purple Ground",
    "capacity": 10321
  },
  "Lille Red": {
    "name": "Villeneuve-d'Ascq Stadium",
    "capacity": 50000,
    "city": "Villeneuve-d'Ascq",
    "country": "France"
  },
  "Fiorita Yellow": {
    "name": "Serravalle Stadium",
    "capacity": 6664,
    "city": "Serravalle",
    "country": "San Marino"
  },
  "Larne Red": {
    "name": "Larne Stadium",
    "capacity": 1100,
    "city": "Larne",
    "country": "United Kingdom"
  },
  "Havre Sky": {
    "name": "Le Havre Stadium",
    "capacity": 33000,
    "city": "Le Havre",
    "country": "France"
  },
  "Poznan Blue": {
    "name": "Poznan Blue Ground",
    "capacity": 42873,
    "country": "Poland"
  },
  "Gdansk Green": {
    "name": "Gdańsk Stadium",
    "capacity": 41620,
    "city": "Gdańsk",
    "country": "Poland"
  },
  "Leeds Yellow": {
    "name": "Leeds Stadium",
    "capacity": 37792,
    "city": "Leeds",
    "country": "United Kingdom"
  },
  "Warszawa Black": {
    "name": "Śródmieście Stadium",
    "capacity": 31106,
    "city": "Śródmieście",
    "country": "Poland"
  },
  "Leicester Blue": {
    "name": "City of Leicester Stadium",
    "capacity": 32261,
    "city": "City of Leicester",
    "country": "United Kingdom"
  },
  "Greece Navy": {
    "name": "Livadia Municipality Stadium",
    "capacity": 5915,
    "city": "Livadia Municipality",
    "country": "Greece"
  },
  "Levante Navy": {
    "name": "Valencia Stadium",
    "capacity": 26354,
    "city": "Valencia",
    "country": "Spain"
  },
  "Sofia Blue": {
    "name": "Poduyane District Stadium",
    "capacity": 29200,
    "city": "Poduyane District",
    "country": "Bulgaria"
  },
  "Imps Red": {
    "name": "Gibraltar Stadium",
    "capacity": 5000,
    "city": "Gibraltar",
    "country": "United Kingdom"
  },
  "Linfield Blue": {
    "name": "Belfast Stadium",
    "capacity": 18500,
    "city": "Belfast",
    "country": "United Kingdom"
  },
  "Gibraltar Orange": {
    "name": "Gibraltar Stadium",
    "capacity": 5000,
    "city": "Gibraltar",
    "country": "United Kingdom"
  },
  "Liverpool Claret": {
    "name": "Liverpool Stadium",
    "capacity": 61276,
    "city": "Liverpool",
    "country": "United Kingdom"
  },
  "Livingston Yellow": {
    "name": "West Lothian Stadium",
    "capacity": 9865,
    "city": "West Lothian",
    "country": "United Kingdom"
  },
  "Llanelli Red": {
    "name": "Llanelli Stadium",
    "capacity": 3700,
    "city": "Llanelli",
    "country": "United Kingdom"
  },
  "Plovdiv Black & White": {
    "name": "Plovdiv Stadium",
    "capacity": 11800,
    "city": "Plovdiv",
    "country": "Bulgaria"
  },
  "Sofia Red & Black": {
    "name": "Stolichna Municipality Stadium",
    "capacity": 22000,
    "city": "Stolichna Municipality",
    "country": "Bulgaria"
  },
  "Razgrad Green": {
    "name": "Razgrad Stadium",
    "capacity": 9000,
    "city": "Razgrad",
    "country": "Bulgaria"
  },
  "Luton Blue": {
    "name": "Luton Stadium",
    "capacity": 10356,
    "city": "Luton",
    "country": "United Kingdom"
  },
  "Lynx Yellow": {
    "name": "Gibraltar Stadium",
    "capacity": 5000,
    "city": "Gibraltar",
    "country": "United Kingdom"
  },
  "Karvina White": {
    "name": "Karviná Stadium",
    "capacity": 8000,
    "city": "Karviná",
    "country": "Czech Republic"
  },
  "Ruzomberok Sky": {
    "name": "Ružomberok Stadium",
    "capacity": 4817,
    "city": "Ružomberok",
    "country": "Slovakia"
  },
  "Skalica Green": {
    "name": "Skalica Stadium",
    "city": "Skalica",
    "country": "Slovakia"
  },
  "Vitebsk Blue": {
    "name": "Vitebsk Region Stadium",
    "capacity": 8144,
    "city": "Vitebsk Region",
    "country": "Belarus"
  },
  "Zilina Yellow": {
    "name": "Žilina Stadium",
    "capacity": 11258,
    "city": "Žilina",
    "country": "Slovakia"
  },
  "Budapest Blue": {
    "name": "Budapest Stadium",
    "capacity": 5322,
    "city": "Budapest",
    "country": "Hungary"
  },
  "Reineh Blue": {
    "name": "Reineh Blue Ground",
    "capacity": 5200
  },
  "Haifa Green": {
    "name": "Haifa Stadium",
    "capacity": 30950,
    "city": "Haifa",
    "country": "Israel"
  },
  "Netanya Yellow": {
    "name": "Netanya Stadium",
    "capacity": 13610,
    "city": "Netanya",
    "country": "Israel"
  },
  "Aviv Yellow": {
    "name": "Tel Aviv Stadium",
    "capacity": 29400,
    "city": "Tel Aviv",
    "country": "Israel"
  },
  "Petrov Yellow": {
    "name": "Petrov Yellow Ground",
    "country": "North Macedonia"
  },
  "Malmö Sky": {
    "name": "Malmö Municipality Stadium",
    "capacity": 22500,
    "city": "Malmö Municipality",
    "country": "Sweden"
  },
  "Manchester Red": {
    "name": "Gibraltar Stadium",
    "capacity": 5000,
    "city": "Gibraltar",
    "country": "United Kingdom"
  },
  "Manchester Sky": {
    "name": "Manchester Stadium",
    "capacity": 52900,
    "city": "Manchester",
    "country": "United Kingdom"
  },
  "Manchester Red & White": {
    "name": "Trafford Stadium",
    "capacity": 75731,
    "city": "Trafford",
    "country": "United Kingdom"
  },
  "Marsaxlokk Blue": {
    "name": "Marsaxlokk Stadium",
    "capacity": 1000,
    "city": "Marsaxlokk",
    "country": "Malta"
  },
  "AIF Yellow": {
    "name": "Sölvesborg Municipality Stadium",
    "capacity": 7500,
    "city": "Sölvesborg Municipality",
    "country": "Sweden"
  },
  "Molde Blue": {
    "name": "Reknes Stadium",
    "capacity": 11800,
    "city": "Reknes",
    "country": "Norway"
  },
  "Calpe Red": {
    "name": "Gibraltar Stadium",
    "capacity": 5000,
    "city": "Gibraltar",
    "country": "United Kingdom"
  },
  "Bulgaria Blue": {
    "name": "Montana Stadium",
    "capacity": 8000,
    "city": "Montana",
    "country": "Bulgaria"
  },
  "HSC Navy": {
    "name": "Montpellier Stadium",
    "capacity": 32900,
    "city": "Montpellier",
    "country": "France"
  },
  "Moreirense Green": {
    "name": "Moreira de Cónegos Stadium",
    "capacity": 6150,
    "city": "Moreira de Cónegos",
    "country": "Portugal"
  },
  "Mosta Blue": {
    "name": "Mosta Stadium",
    "capacity": 600,
    "city": "Mosta",
    "country": "Malta"
  },
  "Motherwell Yellow": {
    "name": "North Lanarkshire Stadium",
    "capacity": 13677,
    "city": "North Lanarkshire",
    "country": "United Kingdom"
  },
  "Lublin Yellow": {
    "name": "Lublin Stadium",
    "capacity": 15247,
    "city": "Lublin",
    "country": "Poland"
  },
  "Breda Yellow": {
    "name": "Breda Stadium",
    "capacity": 19000,
    "city": "Breda",
    "country": "Netherlands"
  },
  "Nijmegen Red": {
    "name": "Nijmegen Stadium",
    "capacity": 12500,
    "city": "Nijmegen",
    "country": "Netherlands"
  },
  "Kidricevo Red": {
    "name": "Municipality of Kidričevo Stadium",
    "capacity": 600,
    "city": "Municipality of Kidričevo",
    "country": "Slovenia"
  },
  "Bravo Yellow": {
    "name": "Bravo Yellow Ground",
    "capacity": 16038
  },
  "Celje Navy": {
    "name": "Hudinja Stadium",
    "capacity": 13006,
    "city": "Hudinja",
    "country": "Slovenia"
  },
  "Istra Yellow": {
    "name": "Pula Stadium",
    "capacity": 9200,
    "city": "Pula",
    "country": "Croatia"
  },
  "Zagreb Blue & White": {
    "name": "Maksimir Stadium",
    "capacity": 60000,
    "city": "Maksimir",
    "country": "Croatia"
  },
  "Maribor Navy": {
    "name": "Maribor City Municipality Stadium",
    "capacity": 12994,
    "city": "Maribor City Municipality",
    "country": "Slovenia"
  },
  "Ljubljana Green": {
    "name": "Ljubljana Stadium",
    "capacity": 16038,
    "city": "Ljubljana",
    "country": "Slovenia"
  },
  "Osijek Sky": {
    "name": "Osijek Stadium",
    "capacity": 13005,
    "city": "Osijek",
    "country": "Croatia"
  },
  "Radomlje Yellow": {
    "name": "Domžale Stadium",
    "capacity": 2813,
    "city": "Domžale",
    "country": "Slovenia"
  },
  "Brijeg Blue": {
    "name": "Široki Brijeg Stadium",
    "capacity": 10000,
    "city": "Široki Brijeg",
    "country": "Bosnia and Herzegovina"
  },
  "Varazdin Blue": {
    "name": "Varaždin Stadium",
    "capacity": 10800,
    "city": "Varaždin",
    "country": "Croatia"
  },
  "Rivne Red": {
    "name": "Rivne Stadium",
    "capacity": 20000,
    "city": "Rivne",
    "country": "Ukraine"
  },
  "Mura Gold": {
    "name": "Murska Sobota Stadium",
    "capacity": 3782,
    "city": "Murska Sobota",
    "country": "Slovenia"
  },
  "Runavík Yellow": {
    "name": "Runavík Municipality Stadium",
    "capacity": 2000,
    "city": "Runavík Municipality",
    "country": "Faroe Islands"
  },
  "Novopolotsk Navy": {
    "name": "Vitebsk Region Stadium",
    "capacity": 4520,
    "city": "Vitebsk Region",
    "country": "Belarus"
  },
  "Lions Red": {
    "name": "Ta' Qali Stadium",
    "capacity": 17797,
    "city": "Ta' Qali",
    "country": "Malta"
  },
  "PFK Black": {
    "name": "Nizami raion Stadium",
    "capacity": 15000,
    "city": "Nizami raion",
    "country": "Azerbaijan"
  },
  "Grodno Green": {
    "name": "Hrodna Region Stadium",
    "capacity": 8479,
    "city": "Hrodna Region",
    "country": "Belarus"
  },
  "Newcastle Black": {
    "name": "Newcastle upon Tyne Stadium",
    "capacity": 52305,
    "city": "Newcastle upon Tyne",
    "country": "United Kingdom"
  },
  "Norwich Yellow": {
    "name": "Norwich Stadium",
    "capacity": 27244,
    "city": "Norwich",
    "country": "United Kingdom"
  },
  "Forest Red": {
    "name": "Rushcliffe Stadium",
    "capacity": 30404,
    "city": "Rushcliffe",
    "country": "United Kingdom"
  },
  "Spartacus Navy": {
    "name": "Spartacus Navy Ground",
    "capacity": 8150,
    "country": "Hungary"
  },
  "Nîmes Blue": {
    "name": "Nîmes Stadium",
    "capacity": 18482,
    "city": "Nîmes",
    "country": "France"
  },
  "Crete Black": {
    "name": "Heraklion Municipality Stadium",
    "capacity": 26240,
    "city": "Heraklion Municipality",
    "country": "Greece"
  },
  "Beograd Blue": {
    "name": "Karaburma Stadium",
    "capacity": 19100,
    "city": "Karaburma",
    "country": "Serbia"
  },
  "Petrovac Sky": {
    "name": "Petrovac na Moru Stadium",
    "capacity": 1500,
    "city": "Petrovac na Moru",
    "country": "Montenegro"
  },
  "Nice Red": {
    "name": "Nice Stadium",
    "capacity": 36178,
    "city": "Nice",
    "country": "France"
  },
  "Kyiv Green": {
    "name": "Kyiv Stadium",
    "capacity": 5103,
    "city": "Kyiv",
    "country": "Ukraine"
  },
  "Boldklub Blue": {
    "name": "Odense Municipality Stadium",
    "capacity": 15633,
    "city": "Odense Municipality",
    "country": "Denmark"
  },
  "Kokshetau Sky": {
    "name": "Kokshetau Stadium",
    "capacity": 4158,
    "city": "Kokshetau",
    "country": "Kazakhstan"
  },
  "Piraeus Red": {
    "name": "Piraeus Municipality Stadium",
    "capacity": 33334,
    "city": "Piraeus Municipality",
    "country": "Greece"
  },
  "Nicosia Black": {
    "name": "Strovolos Stadium",
    "capacity": 22709,
    "city": "Strovolos",
    "country": "Cyprus"
  },
  "Lyon Blue": {
    "name": "Décines-Charpieu Stadium",
    "capacity": 59286,
    "city": "Décines-Charpieu",
    "country": "France"
  },
  "Marseille Navy": {
    "name": "8th arrondissement of Marseille Stadium",
    "capacity": 67394,
    "city": "8th arrondissement of Marseille",
    "country": "France"
  },
  "Aradippou Blue": {
    "name": "Aradhippou Stadium",
    "capacity": 2000,
    "city": "Aradhippou",
    "country": "Cyprus"
  },
  "Nicosia Green": {
    "name": "Strovolos Stadium",
    "capacity": 22709,
    "city": "Strovolos",
    "country": "Cyprus"
  },
  "Shymkent Blue": {
    "name": "Shymkent Stadium",
    "capacity": 20000,
    "city": "Shymkent",
    "country": "Kazakhstan"
  },
  "Oud-Heverlee Red": {
    "name": "Leuven Stadium",
    "capacity": 9493,
    "city": "Leuven",
    "country": "Belgium"
  },
  "Thessaloniki Black": {
    "name": "Thessaloniki Municipality Stadium",
    "capacity": 28703,
    "city": "Thessaloniki Municipality",
    "country": "Greece"
  },
  "Zwolle Blue": {
    "name": "Zwolle Stadium",
    "capacity": 12500,
    "city": "Zwolle",
    "country": "Netherlands"
  },
  "Eindhoven Black": {
    "name": "Eindhoven Stadium",
    "capacity": 36500,
    "city": "Eindhoven",
    "country": "Netherlands"
  },
  "Pafos Blue": {
    "name": "Paphos Stadium",
    "capacity": 8878,
    "city": "Paphos",
    "country": "Cyprus"
  },
  "Linnameeskond Navy": {
    "name": "Paide City Stadium",
    "capacity": 268,
    "city": "Paide City",
    "country": "Estonia"
  },
  "Paksi Green": {
    "name": "Paks Stadium",
    "city": "Paks",
    "country": "Hungary"
  },
  "Greece Green": {
    "name": "Athens Municipality Stadium",
    "capacity": 16003,
    "city": "Athens Municipality",
    "country": "Greece"
  },
  "Greece Yellow": {
    "name": "Agrinio municipality Stadium",
    "capacity": 7500,
    "city": "Agrinio municipality",
    "country": "Greece"
  },
  "Greece Red": {
    "name": "Serres Municipality Stadium",
    "capacity": 9500,
    "city": "Serres Municipality",
    "country": "Greece"
  },
  "Paris Navy": {
    "name": "13th arrondissement of Paris Stadium",
    "capacity": 20000,
    "city": "13th arrondissement of Paris",
    "country": "France"
  },
  "Paris Blue": {
    "name": "16th arrondissement of Paris Stadium",
    "capacity": 47930,
    "city": "16th arrondissement of Paris",
    "country": "France"
  },
  "Parma Black": {
    "name": "Parma Stadium",
    "capacity": 22352,
    "city": "Parma",
    "country": "Italy"
  },
  "Bitola Green": {
    "name": "Bitola Stadium",
    "capacity": 8000,
    "city": "Bitola",
    "country": "North Macedonia"
  },
  "d'Andorra Red": {
    "name": "d'Andorra Red Ground"
  },
  "Penybont Blue": {
    "name": "Penybont Blue Ground",
    "capacity": 1200
  },
  "Ploiesti Yellow": {
    "name": "Ploiești Stadium",
    "capacity": 15500,
    "city": "Ploiești",
    "country": "Romania"
  },
  "Gliwice Blue": {
    "name": "Gliwice Stadium",
    "capacity": 10037,
    "city": "Gliwice",
    "country": "Poland"
  },
  "Pisa Black": {
    "name": "Pisa Stadium",
    "capacity": 10442,
    "city": "Pisa",
    "country": "Italy"
  },
  "Szczecin Black": {
    "name": "Szczecin Stadium",
    "capacity": 21163,
    "city": "Szczecin",
    "country": "Poland"
  },
  "Zhytomyr Green": {
    "name": "Zhytomyr Stadium",
    "capacity": 21928,
    "city": "Zhytomyr",
    "country": "Ukraine"
  },
  "Сhișinău Red": {
    "name": "Chișinău Stadium",
    "capacity": 2888,
    "city": "Chișinău",
    "country": "Moldova"
  },
  "Portadown Red": {
    "name": "Portadown Stadium",
    "capacity": 3940,
    "city": "Portadown",
    "country": "United Kingdom"
  },
  "Akadémia Navy": {
    "name": "Felcsút Stadium",
    "capacity": 3865,
    "city": "Felcsút",
    "country": "Hungary"
  },
  "Vaprus Yellow": {
    "name": "Pärnu City Stadium",
    "capacity": 1501,
    "city": "Pärnu City",
    "country": "Estonia"
  },
  "Qarabağ Black": {
    "name": "Baku Stadium",
    "capacity": 31200,
    "city": "Baku",
    "country": "Azerbaijan"
  },
  "Louvière Green": {
    "name": "Louvière Green Ground",
    "capacity": 8050
  },
  "Leipzig Red": {
    "name": "Leipzig Stadium",
    "capacity": 42000,
    "city": "Leipzig",
    "country": "Germany"
  },
  "Lens Claret": {
    "name": "Lens Stadium",
    "capacity": 38223,
    "city": "Lens",
    "country": "France"
  },
  "Alsace Blue": {
    "name": "Strasbourg Stadium",
    "capacity": 26109,
    "city": "Strasbourg",
    "country": "France"
  },
  "Barcelona Blue": {
    "name": "El Prat de Llobregat Stadium",
    "capacity": 40500,
    "city": "El Prat de Llobregat",
    "country": "Spain"
  },
  "Mallorca Red": {
    "name": "Palma Stadium",
    "capacity": 25736,
    "city": "Palma",
    "country": "Spain"
  },
  "Belgium Purple": {
    "name": "Anderlecht Stadium",
    "capacity": 21500,
    "city": "Anderlecht",
    "country": "Belgium"
  },
  "Luxembourg Blue": {
    "name": "Luxembourg Stadium",
    "capacity": 5814,
    "city": "Luxembourg",
    "country": "Luxembourg"
  },
  "Radom Green": {
    "name": "Radom Stadium",
    "capacity": 13982,
    "city": "Radom",
    "country": "Poland"
  },
  "Częstochowa Red": {
    "name": "Częstochowa Stadium",
    "capacity": 8000,
    "city": "Częstochowa",
    "country": "Poland"
  },
  "Randers Sky": {
    "name": "Randers Municipality Stadium",
    "capacity": 10300,
    "city": "Randers Municipality",
    "country": "Denmark"
  },
  "Scotland Blue": {
    "name": "Angers Stadium",
    "capacity": 18000,
    "city": "Angers",
    "country": "France"
  },
  "Vienna Green": {
    "name": "Hütteldorf Stadium",
    "city": "Hütteldorf",
    "country": "Austria"
  },
  "Vallecano Red": {
    "name": "Vallecas Stadium",
    "capacity": 14708,
    "city": "Vallecas",
    "country": "Spain"
  },
  "Balompié Green": {
    "name": "Seville Stadium",
    "capacity": 60721,
    "city": "Seville",
    "country": "Spain"
  },
  "Madrid Navy": {
    "name": "Chamartín Stadium",
    "capacity": 83186,
    "city": "Chamartín",
    "country": "Spain"
  },
  "Oviedo Blue": {
    "name": "Oviedo City Stadium",
    "capacity": 30500,
    "city": "Oviedo City",
    "country": "Spain"
  },
  "Sociedad Blue": {
    "name": "San Sebastián Stadium",
    "capacity": 40000,
    "city": "San Sebastián",
    "country": "Spain"
  },
  "Valladolid Black": {
    "name": "Valladolid Stadium",
    "capacity": 27618,
    "city": "Valladolid",
    "country": "Spain"
  },
  "Salzburg Claret": {
    "name": "Trafford Stadium",
    "capacity": 75731,
    "city": "Trafford",
    "country": "United Kingdom"
  },
  "Belgrade Red & Gold": {
    "name": "Trafford Stadium",
    "capacity": 75731,
    "city": "Trafford",
    "country": "United Kingdom"
  },
  "Riga Sky": {
    "name": "Riga Stadium",
    "capacity": 8087,
    "city": "Riga",
    "country": "Latvia"
  },
  "Ave Green": {
    "name": "Vila do Conde Stadium",
    "capacity": 5300,
    "city": "Vila do Conde",
    "country": "Portugal"
  },
  "Rosenborg Black": {
    "name": "Trondheim municipality Stadium",
    "capacity": 21423,
    "city": "Trondheim municipality",
    "country": "Norway"
  },
  "Antwerp Red": {
    "name": "Antwerp Stadium",
    "capacity": 5350,
    "city": "Antwerp",
    "country": "Belgium"
  },
  "Charleroi Black": {
    "name": "Charleroi Black Ground",
    "capacity": 14891,
    "country": "Belgium"
  },
  "Lviv Yellow": {
    "name": "Vynnyky Stadium",
    "city": "Vynnyky",
    "country": "Ukraine"
  },
  "Braga Red": {
    "name": "Real, Dume e Semelhe Stadium",
    "capacity": 30286,
    "city": "Real, Dume e Semelhe",
    "country": "Portugal"
  },
  "Faetano Yellow": {
    "name": "Serravalle Stadium",
    "capacity": 6664,
    "city": "Serravalle",
    "country": "San Marino"
  },
  "Freiburg Red": {
    "name": "Freiburg im Breisgau Stadium",
    "capacity": 34700,
    "city": "Freiburg im Breisgau",
    "country": "Germany"
  },
  "Gjilani Red": {
    "name": "Gjilani Red Ground",
    "capacity": 15000,
    "country": "Kosovo"
  },
  "Heerenveen Black": {
    "name": "Heerenveen Stadium",
    "capacity": 26100,
    "city": "Heerenveen",
    "country": "Netherlands"
  },
  "Galati Blue": {
    "name": "Galați Stadium",
    "capacity": 13500,
    "city": "Galați",
    "country": "Romania"
  },
  "Paderborn Black": {
    "name": "Paderborn Stadium",
    "capacity": 15000,
    "city": "Paderborn",
    "country": "Germany"
  },
  "Poltava Red": {
    "name": "Poltava Red Ground",
    "capacity": 680
  },
  "Telstar Blue": {
    "name": "Velsen Stadium",
    "capacity": 5200,
    "city": "Velsen",
    "country": "Netherlands"
  },
  "Altach Yellow": {
    "name": "Altach Stadium",
    "capacity": 8500,
    "city": "Altach",
    "country": "Austria"
  },
  "Eibar Black": {
    "name": "Eibar Stadium",
    "capacity": 8164,
    "city": "Eibar",
    "country": "Spain"
  },
  "Huesca Red": {
    "name": "Huesca Stadium",
    "capacity": 9000,
    "city": "Huesca",
    "country": "Spain"
  },
  "Seinäjoki Black": {
    "name": "Seinäjoki Stadium",
    "capacity": 5817,
    "city": "Seinäjoki",
    "country": "Finland"
  },
  "Brann Red": {
    "name": "Bergen Municipality Stadium",
    "capacity": 16750,
    "city": "Bergen Municipality",
    "country": "Norway"
  },
  "Olomouc Navy": {
    "name": "Olomouc Stadium",
    "capacity": 12566,
    "city": "Olomouc",
    "country": "Czech Republic"
  },
  "Prague Black": {
    "name": "Prague 10 Stadium",
    "capacity": 20800,
    "city": "Prague 10",
    "country": "Czech Republic"
  },
  "Graz Black": {
    "name": "Liebenau Stadium",
    "capacity": 15400,
    "city": "Liebenau",
    "country": "Austria"
  },
  "Nova Yellow": {
    "name": "Nova Yellow Ground",
    "capacity": 432
  },
  "SL Red": {
    "name": "São Domingos de Benfica Stadium",
    "capacity": 68100,
    "city": "São Domingos de Benfica",
    "country": "Portugal"
  },
  "Caen Blue": {
    "name": "Caen Stadium",
    "capacity": 21068,
    "city": "Caen",
    "country": "France"
  },
  "Cailungo Red": {
    "name": "San Marino Stadium",
    "capacity": 500,
    "city": "San Marino",
    "country": "San Marino"
  },
  "Penne Black": {
    "name": "San Marino Stadium",
    "capacity": 500,
    "city": "San Marino",
    "country": "San Marino"
  },
  "Italy Blue": {
    "name": "Ferrara Stadium",
    "capacity": 16134,
    "city": "Ferrara",
    "country": "Italy"
  },
  "Cosmos Green": {
    "name": "Serravalle Stadium",
    "capacity": 6664,
    "city": "Serravalle",
    "country": "San Marino"
  },
  "Folgore/Falciano Red": {
    "name": "Serravalle Stadium",
    "capacity": 6664,
    "city": "Serravalle",
    "country": "San Marino"
  },
  "Lazio Sky": {
    "name": "Rome Stadium",
    "capacity": 70634,
    "city": "Rome",
    "country": "Italy"
  },
  "Murata Black": {
    "name": "San Marino Stadium",
    "capacity": 500,
    "city": "San Marino",
    "country": "San Marino"
  },
  "Pennarossa Red": {
    "name": "Chiesanuova Stadium",
    "capacity": 300,
    "city": "Chiesanuova",
    "country": "San Marino"
  },
  "Giovanni Red": {
    "name": "Borgo Maggiore Stadium",
    "capacity": 1000,
    "city": "Borgo Maggiore",
    "country": "San Marino"
  },
  "Napoli White": {
    "name": "Naples Stadium",
    "capacity": 54726,
    "city": "Naples",
    "country": "Italy"
  },
  "Darmstadt Blue": {
    "name": "Darmstadt Stadium",
    "capacity": 19000,
    "city": "Darmstadt",
    "country": "Germany"
  },
  "Ried Green": {
    "name": "Ried Green Ground",
    "capacity": 7680,
    "country": "Austria"
  },
  "Bremen Green": {
    "name": "Östliche Vorstadt Stadium",
    "capacity": 42500,
    "city": "Östliche Vorstadt",
    "country": "Germany"
  },
  "Sabah Black": {
    "name": "Masazır Stadium",
    "capacity": 13000,
    "city": "Masazır",
    "country": "Azerbaijan"
  },
  "Turkey Red & White": {
    "name": "Tekkeköy district Stadium",
    "capacity": 33919,
    "city": "Tekkeköy district",
    "country": "Turkey"
  },
  "Fotball Blue": {
    "name": "Sandefjord Stadium",
    "capacity": 6582,
    "city": "Sandefjord",
    "country": "Norway"
  },
  "Sarpsborg Blue": {
    "name": "Sarpsborg Stadium",
    "capacity": 4700,
    "city": "Sarpsborg",
    "country": "Norway"
  },
  "Sofia Claret": {
    "name": "Sofia Claret Ground",
    "country": "Bulgaria"
  },
  "Servette Claret": {
    "name": "Canton of Geneva Stadium",
    "capacity": 30084,
    "city": "Canton of Geneva",
    "country": "Switzerland"
  },
  "Sevilla Red": {
    "name": "Seville Stadium",
    "capacity": 43751,
    "city": "Seville",
    "country": "Spain"
  },
  "Donetsk Orange": {
    "name": "Donetsk Stadium",
    "capacity": 52518,
    "city": "Donetsk",
    "country": "Ukraine"
  },
  "Shamrock Green": {
    "name": "Tallaght Stadium",
    "capacity": 6000,
    "city": "Tallaght",
    "country": "Ireland"
  },
  "Sheffield Red": {
    "name": "Sheffield Stadium",
    "capacity": 32702,
    "city": "Sheffield",
    "country": "United Kingdom"
  },
  "Shelbourne Red": {
    "name": "Drumcondra Stadium",
    "capacity": 9680,
    "city": "Drumcondra",
    "country": "Ireland"
  },
  "Tetovo Red": {
    "name": "Tetovo Stadium",
    "capacity": 15000,
    "city": "Tetovo",
    "country": "North Macedonia"
  },
  "Kratovo Blue": {
    "name": "Kratovo Stadium",
    "capacity": 1800,
    "city": "Kratovo",
    "country": "North Macedonia"
  },
  "Silkeborg Red": {
    "name": "Silkeborg Municipality Stadium",
    "city": "Silkeborg Municipality",
    "country": "Denmark"
  },
  "Sint-Truidense Yellow": {
    "name": "Sint-Truiden Stadium",
    "capacity": 11250,
    "city": "Sint-Truiden",
    "country": "Belgium"
  },
  "Koprivnica Blue": {
    "name": "Koprivnica Stadium",
    "capacity": 4000,
    "city": "Koprivnica",
    "country": "Croatia"
  },
  "Mozyr Red": {
    "name": "Mazyr district Stadium",
    "capacity": 5133,
    "city": "Mazyr district",
    "country": "Belarus"
  },
  "Sofia Black": {
    "name": "Stolichna Municipality Stadium",
    "capacity": 15992,
    "city": "Stolichna Municipality",
    "country": "Bulgaria"
  },
  "Sliema Blue": {
    "name": "Ta' Qali Stadium",
    "capacity": 17797,
    "city": "Ta' Qali",
    "country": "Malta"
  },
  "Sligo Red": {
    "name": "Sligo Stadium",
    "capacity": 4500,
    "city": "Sligo",
    "country": "Ireland"
  },
  "Bratislava Sky": {
    "name": "Bratislava Stadium",
    "capacity": 13000,
    "city": "Bratislava",
    "country": "Slovakia"
  },
  "Southampton Black": {
    "name": "Southampton Stadium",
    "capacity": 32589,
    "city": "Southampton",
    "country": "United Kingdom"
  },
  "Fürth Green": {
    "name": "Fürth Stadium",
    "capacity": 18500,
    "city": "Fürth",
    "country": "Germany"
  },
  "Rotterdam Black & White": {
    "name": "Rotterdam Stadium",
    "capacity": 11026,
    "city": "Rotterdam",
    "country": "Netherlands"
  },
  "Trnava Red": {
    "name": "Trnava Stadium",
    "capacity": 19200,
    "city": "Trnava",
    "country": "Slovakia"
  },
  "Varna Blue": {
    "name": "Varna Stadium",
    "capacity": 8000,
    "city": "Varna",
    "country": "Bulgaria"
  },
  "Spezia Black": {
    "name": "La Spezia Stadium",
    "capacity": 12037,
    "city": "La Spezia",
    "country": "Italy"
  },
  "CP Black": {
    "name": "Lumiar Stadium",
    "capacity": 52095,
    "city": "Lumiar",
    "country": "Portugal"
  },
  "Joseph's Blue": {
    "name": "Gibraltar Stadium",
    "capacity": 5000,
    "city": "Gibraltar",
    "country": "United Kingdom"
  },
  "Mirren Yellow": {
    "name": "Renfrewshire Stadium",
    "capacity": 8023,
    "city": "Renfrewshire",
    "country": "United Kingdom"
  },
  "F.C. Yellow": {
    "name": "Żabbar Stadium",
    "capacity": 1000,
    "city": "Żabbar",
    "country": "Malta"
  },
  "Patrick's Red": {
    "name": "Dublin Stadium",
    "capacity": 5340,
    "city": "Dublin",
    "country": "Ireland"
  },
  "Brestois Red": {
    "name": "Brest Stadium",
    "capacity": 15097,
    "city": "Brest",
    "country": "France"
  },
  "Reims Red": {
    "name": "Reims Stadium",
    "capacity": 21684,
    "city": "Reims",
    "country": "France"
  },
  "Rennais Red": {
    "name": "Rennes Stadium",
    "capacity": 31127,
    "city": "Rennes",
    "country": "France"
  },
  "Liège Red": {
    "name": "Liège Stadium",
    "capacity": 30023,
    "city": "Liège",
    "country": "Belgium"
  },
  "Gardabaer Blue": {
    "name": "Garðabær Stadium",
    "capacity": 1000,
    "city": "Garðabær",
    "country": "Iceland"
  },
  "Lum Red": {
    "name": "Struga Stadium",
    "capacity": 500,
    "city": "Struga",
    "country": "North Macedonia"
  },
  "Toppfotball Navy": {
    "name": "Drammen Stadium",
    "capacity": 7500,
    "city": "Drammen",
    "country": "Norway"
  },
  "PFC Purple": {
    "name": "Sumgait Stadium",
    "capacity": 15350,
    "city": "Sumgait",
    "country": "Azerbaijan"
  },
  "Sunderland Red": {
    "name": "Sunderland Stadium",
    "capacity": 48339,
    "city": "Sunderland",
    "country": "United Kingdom"
  },
  "Hesperange Red": {
    "name": "Hesperange Stadium",
    "capacity": 4100,
    "city": "Hesperange",
    "country": "Luxembourg"
  },
  "Fodbold Sky": {
    "name": "Haderslev Municipality Stadium",
    "capacity": 10000,
    "city": "Haderslev Municipality",
    "country": "Denmark"
  },
  "Hoffenheim Blue": {
    "name": "Sinsheim Stadium",
    "capacity": 30150,
    "city": "Sinsheim",
    "country": "Germany"
  },
  "Hartberg Blue": {
    "name": "Hartberg Stadium",
    "capacity": 4500,
    "city": "Hartberg",
    "country": "Austria"
  },
  "Rainbows Sky": {
    "name": "Ta' Qali Stadium",
    "capacity": 17797,
    "city": "Ta' Qali",
    "country": "Malta"
  },
  "Saints Blue": {
    "name": "Oswestry Stadium",
    "capacity": 2056,
    "city": "Oswestry",
    "country": "United Kingdom"
  },
  "Kavadarci Red": {
    "name": "Kavadarci Stadium",
    "capacity": 7500,
    "city": "Kavadarci",
    "country": "North Macedonia"
  },
  "Kostanay Black": {
    "name": "Kostanay Stadium",
    "capacity": 8323,
    "city": "Kostanay",
    "country": "Kazakhstan"
  },
  "Italy Claret": {
    "name": "Turin Stadium",
    "capacity": 28177,
    "city": "Turin",
    "country": "Italy"
  },
  "Kutaisi Black": {
    "name": "Kutaisi Stadium",
    "capacity": 10700,
    "city": "Kutaisi",
    "country": "Georgia"
  },
  "Torpedo-BelAZ Black": {
    "name": "Minsk region Stadium",
    "capacity": 6524,
    "city": "Minsk region",
    "country": "Belarus"
  },
  "Tottenham Black": {
    "name": "Tottenham Stadium",
    "capacity": 62850,
    "city": "Tottenham",
    "country": "United Kingdom"
  },
  "Turkey Claret": {
    "name": "Trabzon Stadium",
    "capacity": 41500,
    "city": "Trabzon",
    "country": "Turkey"
  },
  "Fiori Yellow": {
    "name": "Fiorentino Stadium",
    "city": "Fiorentino",
    "country": "San Marino"
  },
  "IL Black": {
    "name": "Tromsø Municipality Stadium",
    "capacity": 6859,
    "city": "Tromsø Municipality",
    "country": "Norway"
  },
  "Turan-Tovuz Red": {
    "name": "Tovuz Stadium",
    "capacity": 6480,
    "city": "Tovuz",
    "country": "Azerbaijan"
  },
  "Sampdoria Blue": {
    "name": "Genoa Stadium",
    "capacity": 33205,
    "city": "Genoa",
    "country": "Italy"
  },
  "Almería Red": {
    "name": "Almería Stadium",
    "capacity": 22000,
    "city": "Almería",
    "country": "Spain"
  },
  "Palmas Yellow": {
    "name": "Las Palmas de Gran Canaria Stadium",
    "capacity": 32392,
    "city": "Las Palmas de Gran Canaria",
    "country": "Spain"
  },
  "Coloma Black & Yellow": {
    "name": "Aixovall Stadium",
    "capacity": 1000,
    "city": "Aixovall",
    "country": "Andorra"
  },
  "Afturelding Red": {
    "name": "Afturelding Red Ground",
    "capacity": 2500
  },
  "Käerjeng Navy": {
    "name": "Käerjeng Stadium",
    "city": "Käerjeng",
    "country": "Luxembourg"
  },
  "Cremonese Red": {
    "name": "Cremona Stadium",
    "capacity": 15191,
    "city": "Cremona",
    "country": "Italy"
  },
  "Hostert Black": {
    "name": "Hostert Black Ground",
    "capacity": 1500
  },
  "Lecce Yellow": {
    "name": "Lecce Stadium",
    "capacity": 31461,
    "city": "Lecce",
    "country": "Italy"
  },
  "Mondorf-Les-Bains Sky": {
    "name": "Mondorf-Les-Bains Sky Ground"
  },
  "Salernitana Claret": {
    "name": "Salerno Stadium",
    "capacity": 37245,
    "city": "Salerno",
    "country": "Italy"
  },
  "Sassuolo Green": {
    "name": "Reggio Emilia Stadium",
    "capacity": 21525,
    "city": "Reggio Emilia",
    "country": "Italy"
  },
  "Arad Red": {
    "name": "Arad Stadium",
    "capacity": 7287,
    "city": "Arad",
    "country": "Romania"
  },
  "Udinese Gold": {
    "name": "Udine Stadium",
    "capacity": 25312,
    "city": "Udine",
    "country": "Italy"
  },
  "Saint-Gilloise Yellow": {
    "name": "Forest Stadium",
    "capacity": 5100,
    "city": "Forest",
    "country": "Belgium"
  },
  "Petange Blue": {
    "name": "Pétange Stadium",
    "capacity": 2400,
    "city": "Pétange",
    "country": "Luxembourg"
  },
  "Craiova Blue": {
    "name": "Craiova Stadium",
    "capacity": 30944,
    "city": "Craiova",
    "country": "Romania"
  },
  "Palloseura Black": {
    "name": "Vaasa Stadium",
    "capacity": 6009,
    "city": "Vaasa",
    "country": "Finland"
  },
  "Valencia Black": {
    "name": "Valencia Black Ground",
    "capacity": 49430,
    "country": "Spain"
  },
  "Valletta Red": {
    "name": "Ta' Qali Stadium",
    "capacity": 17797,
    "city": "Ta' Qali",
    "country": "Malta"
  },
  "Reykjavík Red": {
    "name": "Hlíðar Stadium",
    "capacity": 3000,
    "city": "Hlíðar",
    "country": "Iceland"
  },
  "Skopje Black": {
    "name": "Centar Municipality Stadium",
    "capacity": 33460,
    "city": "Centar Municipality",
    "country": "North Macedonia"
  },
  "Boldklub Red": {
    "name": "Vejle Municipality Stadium",
    "capacity": 10418,
    "city": "Vejle Municipality",
    "country": "Denmark"
  },
  "Venezia Black": {
    "name": "Venice Stadium",
    "capacity": 10500,
    "city": "Venice",
    "country": "Italy"
  },
  "Iceland Navy": {
    "name": "Iceland Navy Ground",
    "capacity": 1596
  },
  "Stuttgart Red": {
    "name": "Bad Cannstatt Stadium",
    "capacity": 60058,
    "city": "Bad Cannstatt",
    "country": "Germany"
  },
  "Bochum Navy": {
    "name": "Bochum Stadium",
    "capacity": 29299,
    "city": "Bochum",
    "country": "Germany"
  },
  "Wolfsburg Navy": {
    "name": "Wolfsburg Stadium",
    "capacity": 30000,
    "city": "Wolfsburg",
    "country": "Germany"
  },
  "Viborg Green": {
    "name": "Viborg Municipality Stadium",
    "capacity": 10000,
    "city": "Viborg Municipality",
    "country": "Denmark"
  },
  "Viking Black": {
    "name": "Stavanger Stadium",
    "capacity": 15400,
    "city": "Stavanger",
    "country": "Norway"
  },
  "Spain Yellow": {
    "name": "Villarreal Stadium",
    "capacity": 24891,
    "city": "Villarreal",
    "country": "Spain"
  },
  "Guimarães Black": {
    "name": "Guimarães Stadium",
    "capacity": 30029,
    "city": "Guimarães",
    "country": "Portugal"
  },
  "NFC Red": {
    "name": "Volos Municipality Stadium",
    "capacity": 22700,
    "city": "Volos Municipality",
    "country": "Greece"
  },
  "Elite Blue": {
    "name": "Oslo Stadium",
    "capacity": 17333,
    "city": "Oslo",
    "country": "Norway"
  },
  "Gøta Sky": {
    "name": "Gøta Sky Ground",
    "country": "Faroe Islands"
  },
  "Reykjavík Black & White": {
    "name": "Reykjavík Black & White Ground",
    "country": "Iceland"
  },
  "Tirol Green": {
    "name": "Innsbruck Stadium",
    "capacity": 17400,
    "city": "Innsbruck",
    "country": "Austria"
  },
  "Waterford Blue": {
    "name": "Waterford Stadium",
    "capacity": 3100,
    "city": "Waterford",
    "country": "Ireland"
  },
  "Watford Yellow": {
    "name": "Watford Stadium",
    "capacity": 22000,
    "city": "Watford",
    "country": "United Kingdom"
  },
  "Bromwich Navy": {
    "name": "West Bromwich Stadium",
    "capacity": 26445,
    "city": "West Bromwich",
    "country": "United Kingdom"
  },
  "Ham Claret": {
    "name": "Stratford Stadium",
    "capacity": 62500,
    "city": "Stratford",
    "country": "United Kingdom"
  },
  "Lodz Red": {
    "name": "Stary Widzew Stadium",
    "capacity": 18018,
    "city": "Stary Widzew",
    "country": "Poland"
  },
  "Plock Blue": {
    "name": "Płock Stadium",
    "capacity": 15004,
    "city": "Płock",
    "country": "Poland"
  },
  "Wolfsberger Blue": {
    "name": "Wolfsberg Stadium",
    "capacity": 7300,
    "city": "Wolfsberg",
    "country": "Austria"
  },
  "Wolverhampton Yellow": {
    "name": "Wolverhampton Stadium",
    "capacity": 30852,
    "city": "Wolverhampton",
    "country": "United Kingdom"
  },
  "Semey Green": {
    "name": "Semey Green Ground",
    "capacity": 8196
  },
  "Lubin Orange": {
    "name": "Lubin Stadium",
    "capacity": 16068,
    "city": "Lubin",
    "country": "Poland"
  },
  "TE Blue": {
    "name": "Zalaegerszeg Stadium",
    "capacity": 14000,
    "city": "Zalaegerszeg",
    "country": "Hungary"
  },
  "Podbrezova Black": {
    "name": "Podbrezová Stadium",
    "capacity": 4500,
    "city": "Podbrezová",
    "country": "Slovakia"
  },
  "Michalovce Yellow": {
    "name": "Michalovce Stadium",
    "capacity": 4500,
    "city": "Michalovce",
    "country": "Slovakia"
  },
  "Astana Yellow & Black": {
    "name": "Astana Stadium",
    "capacity": 12350,
    "city": "Astana",
    "country": "Kazakhstan"
  },
  "Taldykorgan Blue": {
    "name": "Taldyqorğan Stadium",
    "capacity": 4000,
    "city": "Taldyqorğan",
    "country": "Kazakhstan"
  },
  "Zira Sky": {
    "name": "Zira Sky Ground",
    "capacity": 1500,
    "country": "Azerbaijan"
  },
  "Lugansk Red": {
    "name": "Luhansk Stadium",
    "capacity": 22288,
    "city": "Luhansk",
    "country": "Ukraine"
  },
  "Waregem Red": {
    "name": "Waregem Stadium",
    "capacity": 10200,
    "city": "Waregem",
    "country": "Belgium"
  },
  "Akranes Yellow": {
    "name": "Akranes Stadium",
    "capacity": 4850,
    "city": "Akranes",
    "country": "Iceland"
  },
  "Vestmannaeyjar Blue": {
    "name": "Vestmannaeyjar Stadium",
    "capacity": 3540,
    "city": "Vestmannaeyjar",
    "country": "Iceland"
  },
  "Sweden Red": {
    "name": "Sweden Red Ground",
    "capacity": 12000
  },
  "Újpest Purple": {
    "name": "Budapest District IV Stadium",
    "capacity": 13501,
    "city": "Budapest District IV",
    "country": "Hungary"
  }
}
